// ─── Allka — Central Indicator & Report Catalog ───────────────────────────────
// Authoritative source of truth for every KPI indicator and tabular report
// in the platform. Used by:
//   • Frontend: rendering decisions, permission checks, filter controls
//   • Backend planning: which endpoints to build, which Prisma models to query
//
// Data availability key:
//   "available" → computable from existing Prisma models today
//   "partial"   → data exists but has gaps or requires non-trivial derivation
//   "missing"   → requires new DB models, events or external integrations

import type {
  IndicatorDefinition,
  TabularReportDefinition,
} from "../types/indicator.types";

// ═══════════════════════════════════════════════════════════════════════════════
// ADMIN — KPI INDICATORS
// ═══════════════════════════════════════════════════════════════════════════════

export const ADMIN_INDICATORS: IndicatorDefinition[] = [
  // ── 1. Faturamento ──────────────────────────────────────────────────────────
  {
    id: "faturamento",
    name: "Faturamento",
    description: "Valor total faturado no período filtrado versus mesmo período anterior.",
    purpose: "Medir crescimento de receita e identificar variações sazonais.",
    profiles: ["admin"],
    category: "financial",
    visualType: ["kpi_comparison", "line_chart"],
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["Invoice"],
    dataAvailability: "available",
    notes: "Usar Invoice.paid_at para faturamento realizado. Invoice.status='paid'. Comparação: mesmo intervalo de datas do período anterior.",
  },

  // ── 2. Carteira ─────────────────────────────────────────────────────────────
  {
    id: "carteira",
    name: "Carteira",
    description: "Saldo disponível para saque, saldo bloqueado e créditos internos da plataforma por carteira.",
    purpose: "Visibilidade do fluxo de crédito dentro da plataforma (nômades, agências, parceiros).",
    profiles: ["admin"],
    category: "financial",
    visualType: "kpi",
    allowedScopes: ["GLOBAL"],
    allowsComparison: false,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: true,
    dependencies: ["Wallet", "WalletLedger"],
    dataAvailability: "available",
    notes: "Wallet.balance = disponível. Wallet.blocked_balance = bloqueado. Agrupar por Wallet.owner_type (nomad/agency/partner/platform).",
  },

  // ── 3. MRR ──────────────────────────────────────────────────────────────────
  {
    id: "mrr",
    name: "MRR",
    description: "Receita mensal recorrente de produtos/projetos mensais ativos no período.",
    purpose: "Medir previsibilidade de receita e crescimento de base recorrente.",
    profiles: ["admin"],
    category: "financial",
    visualType: ["kpi_comparison", "line_chart"],
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["Invoice", "Project"],
    dataAvailability: "partial",
    missingFields: [
      "Project.agency é string (não FK) — filtrar projetos mensais por agência requer JOIN textual ou campo extra",
      "Não há campo explícito de MRR por agência/período — deve ser derivado de Invoice + Project.lifecycle='mensal'",
    ],
    notes: "Filtrar Project.lifecycle='mensal', somar Invoice.amount dos projetos mensais pagos no período. Para previsão futura, somar valor dos projetos mensais ativos sem fatura vencida.",
  },

  // ── 4. Avulsos ──────────────────────────────────────────────────────────────
  {
    id: "avulsos",
    name: "Avulsos",
    description: "Total de produtos/projetos avulsos faturados no período.",
    purpose: "Medir receita não-recorrente separada do MRR.",
    profiles: ["admin"],
    category: "financial",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["Invoice", "Project"],
    dataAvailability: "partial",
    missingFields: [
      "Mesma limitação de Project.agency como string",
    ],
    notes: "Project.lifecycle='avulso'. Cruzar com Invoice para obter o valor real pago.",
  },

  // ── 5. Checkout do Cliente ───────────────────────────────────────────────────
  {
    id: "checkout_cliente",
    name: "Checkout do Cliente",
    description: "Projetos contratados diretamente pelo cliente final (empresa), com total, margem média das agências e crescimento.",
    purpose: "Medir volume de vendas geradas pelo checkout direto versus agência.",
    profiles: ["admin"],
    category: "financial",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["Project", "Invoice", "Company"],
    dataAvailability: "partial",
    missingFields: [
      "Project.company_type='company' identifica checkout direto, mas margem da agência não está armazenada no Invoice — está em ProjectProduct.comissao_snapshot",
      "Modelo de margem média requer ProjectProduct.preco_final_cliente_snapshot vs. base price",
    ],
    notes: "Project.company_type='company' = checkout do cliente. Margem = (preco_final_cliente_snapshot - product.base_price) / preco_final_cliente_snapshot. Usar ProjectProduct para o cálculo.",
  },

  // ── 6. Plano de Crédito ──────────────────────────────────────────────────────
  {
    id: "plano_credito",
    name: "Plano de Crédito",
    description: "Total de planos de crédito Squad ativos, valor e crescimento no período.",
    purpose: "Medir adesão ao modelo pós-pago de crédito.",
    profiles: ["admin"],
    category: "financial",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["SquadConfig", "SquadCycle"],
    dataAvailability: "available",
    notes: "SquadConfig.status='active'. SquadCycle.total_invoiced para valor do período. Novos planos = SquadConfig.started_at no período.",
  },

  // ── 7. Novos MRR ────────────────────────────────────────────────────────────
  {
    id: "novos_mrr",
    name: "Novos MRR",
    description: "Itens mensais contratados pela primeira vez no período, com valor e crescimento.",
    purpose: "Separar crescimento orgânico de MRR de expansão de base existente.",
    profiles: ["admin"],
    category: "financial",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["Project", "Invoice"],
    dataAvailability: "partial",
    missingFields: [
      "Não há flag 'first_contract' em Project — 'novo MRR' requer verificar se agência nunca teve Project.lifecycle='mensal' antes",
    ],
    notes: "Filtrar projetos mensais criados no período onde a agência não tinha projeto mensal ativo antes.",
  },

  // ── 8. Novos Avulsos ────────────────────────────────────────────────────────
  {
    id: "novos_avulsos",
    name: "Novos Avulsos",
    description: "Itens avulsos contratados no período, com valor e crescimento.",
    purpose: "Medir demanda por produtos pontuais.",
    profiles: ["admin"],
    category: "financial",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["Project", "Invoice"],
    dataAvailability: "partial",
    missingFields: ["Mesma limitação de Project.agency como string"],
    notes: "Project.lifecycle='avulso' criados no período filtrado.",
  },

  // ── 9. Churn de Projetos ─────────────────────────────────────────────────────
  {
    id: "churn_projetos",
    name: "Churn de Projetos",
    description: "Total de itens recorrentes cancelados no período e percentual sobre faturamento esperado.",
    purpose: "Monitorar perda de receita recorrente.",
    profiles: ["admin"],
    category: "financial",
    visualType: "kpi_alert",
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["Project"],
    dataAvailability: "partial",
    missingFields: [
      "Não há campo Project.cancelled_at ou evento de cancelamento com timestamp",
      "Não há distinção entre 'projeto cancelado' e 'projeto perdido' no status atual — ambos usam status='cancelled'",
      "Não há histórico de mudança de status (audit trail) — impossível saber exatamente quando o projeto virou 'cancelado'",
    ],
    notes: "Usar Project.status='cancelled' + Project.lifecycle='mensal' + Project.updated_at no período como aproximação. Para precisão total, adicionar campo churn_at e/ou tabela de histórico de status.",
  },

  // ── 10. Churn de Agências ────────────────────────────────────────────────────
  {
    id: "churn_agencias",
    name: "Churn de Agências",
    description: "Planos de crédito cancelados no período e percentual sobre faturamento de planos.",
    purpose: "Medir retenção de agências no modelo pós-pago.",
    profiles: ["admin"],
    category: "financial",
    visualType: "kpi_alert",
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["SquadConfig", "Agency"],
    dataAvailability: "partial",
    missingFields: [
      "SquadConfig.ended_at não existe — apenas status='cancelled' sem data de cancelamento",
      "Regra: agências antigas sem plano de crédito devem ser consideradas ativas (não churn) — requer flag ou exceção manual",
    ],
    notes: "SquadConfig.status='cancelled'. Adicionar campo cancelled_at ao SquadConfig para rastrear data exata de cancelamento.",
  },

  // ── 11. Ticket Médio ─────────────────────────────────────────────────────────
  {
    id: "ticket_medio",
    name: "Ticket Médio",
    description: "Valor total de contratações no período dividido pelo número de agências que contrataram.",
    purpose: "Medir valor médio por cliente ativo.",
    profiles: ["admin"],
    category: "financial",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["Invoice", "Project", "Agency"],
    dataAvailability: "partial",
    missingFields: [
      "Project.agency é string — associar Invoice à Agency requer cruzar Project.agency (nome) com Agency.name, o que é frágil",
    ],
    notes: "Idealmente adicionar Project.agency_id (FK para Agency.id). Enquanto isso, derivar via Project.agency (string) → Agency.name.",
  },

  // ── 12. LTV ──────────────────────────────────────────────────────────────────
  {
    id: "ltv",
    name: "LTV",
    description: "Soma histórica de contratações por agências com pelo menos uma contratação nos últimos 3 meses, dividida pelo número dessas agências.",
    purpose: "Estimar valor de longo prazo de um cliente.",
    profiles: ["admin"],
    category: "financial",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["Invoice", "Project", "Agency"],
    dataAvailability: "partial",
    missingFields: [
      "Mesma limitação de Project.agency como string para associar fatura à agência",
    ],
    notes: "Considerar ativas agências com Invoice nos últimos 90 dias. Somar total de Invoice.amount por agência (histórico). Dividir pelo n.º de agências ativas.",
  },

  // ── 13. CMV ──────────────────────────────────────────────────────────────────
  {
    id: "cmv",
    name: "CMV",
    description: "Custo de Mercadoria Vendida: valor pago aos nômades + comissões de parceiros + 16% de impostos.",
    purpose: "Medir custo real de entrega e alertar quando margem está comprometida.",
    profiles: ["admin"],
    category: "financial",
    visualType: ["kpi_alert", "bar_chart"],
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["WalletTransaction", "PartnerCommission", "Invoice", "Project"],
    dataAvailability: "partial",
    missingFields: [
      "Taxa de imposto (16%) não está armazenada no DB — deve ser constante configurável",
      "WalletTransaction não tem link direto a Project/Invoice — difícil atribuir CMV por projeto",
      "PartnerCommission não tem link a Project diretamente",
    ],
    notes: "CMV = Σ(WalletTransaction.amount onde type='credit' para nômade no período) + Σ(PartnerCommission.amount aprovado) + 16% sobre Invoice total. Alerta quando CMV > 50% do Invoice.",
  },

  // ── 14. Margem Bruta ─────────────────────────────────────────────────────────
  {
    id: "margem_bruta",
    name: "Margem Bruta",
    description: "Faturamento total menos CMV, em valor absoluto e percentual.",
    purpose: "Medir rentabilidade operacional antes de despesas fixas.",
    profiles: ["admin"],
    category: "financial",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["Invoice", "WalletTransaction", "PartnerCommission"],
    dataAvailability: "partial",
    missingFields: ["Depende do CMV — herda as mesmas limitações"],
    notes: "Derivado: Margem Bruta = Faturamento - CMV.",
  },

  // ── 15. Projetos Ativos ───────────────────────────────────────────────────────
  {
    id: "projetos_ativos",
    name: "Projetos Ativos",
    description: "Total de projetos em andamento, quantidade de novos produtos contratados e crescimento.",
    purpose: "Medir volume operacional corrente.",
    profiles: ["admin", "agency"],
    category: "projects",
    visualType: ["kpi_comparison", "donut_chart"],
    allowedScopes: ["GLOBAL", "OWN_AGENCY_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["Project"],
    dataAvailability: "available",
    notes: "Project.status IN ('planning','in-progress'). Excluir avulsos concluídos (status='completed' + lifecycle='avulso').",
  },

  // ── 16. Projetos em Rascunho ─────────────────────────────────────────────────
  {
    id: "projetos_rascunho",
    name: "Projetos em Rascunho",
    description: "Total de projetos em rascunho no período e comparação com período anterior.",
    purpose: "Medir pipeline inicial de vendas.",
    profiles: ["admin", "agency"],
    category: "projects",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL", "OWN_AGENCY_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["Project"],
    dataAvailability: "available",
    notes: "Project.status='draft'. Usar Project.created_at para filtrar pelo período.",
  },

  // ── 17. Projetos em Negociação ───────────────────────────────────────────────
  {
    id: "projetos_negociacao",
    name: "Projetos em Negociação",
    description: "Total de projetos em negociação no período e comparação.",
    purpose: "Medir funil de conversão de vendas.",
    profiles: ["admin", "agency"],
    category: "projects",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL", "OWN_AGENCY_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["Project"],
    dataAvailability: "available",
    notes: "Project.status='negotiation'.",
  },

  // ── 18. Projetos Perdidos ────────────────────────────────────────────────────
  {
    id: "projetos_perdidos",
    name: "Projetos Perdidos",
    description: "Total de projetos perdidos/cancelados no período e comparação.",
    purpose: "Medir perda de negócios e identificar gargalos do funil.",
    profiles: ["admin", "agency"],
    category: "projects",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL", "OWN_AGENCY_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["Project"],
    dataAvailability: "partial",
    missingFields: [
      "Project.status='cancelled' agrupa perdidos e cancelados — não há distinção entre 'perdido em negociação' e 'cancelado após contratação'",
      "Sem campo lost_at com timestamp",
    ],
    notes: "Usar Project.status='cancelled' + Project.updated_at no período como aproximação.",
  },

  // ── 19. Nômades ──────────────────────────────────────────────────────────────
  {
    id: "nomades",
    name: "Nômades",
    description: "Total de nômades ativos, novos cadastros, cancelamentos e crescimento. Filtrável por categoria.",
    purpose: "Monitorar saúde e crescimento da base de profissionais.",
    profiles: ["admin"],
    category: "nomads",
    visualType: ["kpi_comparison", "bar_chart"],
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: true,
    dependencies: ["Nomade", "NomadeLevel"],
    dataAvailability: "available",
    notes: "Nomade.status='ativo'. Novos = Nomade.registration_date no período. Cancelados = Nomade.status='inativo' + updated_at no período. Filtro de categoria via Nomade.areas_of_interest (JSON).",
  },

  // ── 20. Pontuação dos Nômades ────────────────────────────────────────────────
  {
    id: "pontuacao_nomades",
    name: "Pontuação dos Nômades",
    description: "Pontuação média dos nômades ativos no período, comparação com período anterior. Filtrável por categoria.",
    purpose: "Medir qualidade geral da base de profissionais.",
    profiles: ["admin"],
    category: "nomads",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: true,
    dependencies: ["Nomade"],
    dataAvailability: "available",
    notes: "AVG(Nomade.score). Filtro de categoria via Nomade.areas_of_interest. Comparação de período requer snapshot histórico do score — atualmente só o valor atual é armazenado.",
  },

  // ── 21. Tarefas Contratadas ───────────────────────────────────────────────────
  {
    id: "tarefas_contratadas",
    name: "Tarefas Contratadas",
    description: "Número de tarefas geradas/lançadas no período e crescimento. Filtrável por categoria.",
    purpose: "Medir volume operacional de entrada.",
    profiles: ["admin", "agency"],
    category: "tasks",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL", "OWN_AGENCY_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: true,
    allowsFilter: true,
    dependencies: ["ProjectTask"],
    dataAvailability: "available",
    notes: "COUNT(ProjectTask) com ProjectTask.created_at no período. Filtro: ProjectTask.category_snapshot.",
  },

  // ── 22. Tarefas Concluídas ────────────────────────────────────────────────────
  {
    id: "tarefas_concluidas",
    name: "Tarefas Concluídas",
    description: "Total de tarefas concluídas até entrega de arquivos finais no período. Filtrável por categoria.",
    purpose: "Medir volume de entrega e velocidade operacional.",
    profiles: ["admin", "agency", "nomad", "leader"],
    category: "tasks",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL", "OWN_AGENCY_SCOPE", "OWN_NOMAD_SCOPE", "OWN_LEADER_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: true,
    allowsFilter: true,
    dependencies: ["ProjectTask"],
    dataAvailability: "available",
    notes: "ProjectTask.status='CONCLUIDA' + ProjectTask.data_conclusao no período. Filtro: category_snapshot.",
  },

  // ── 23. Tarefas Atrasadas ─────────────────────────────────────────────────────
  {
    id: "tarefas_atrasadas",
    name: "Tarefas Atrasadas",
    description: "Total de tarefas atrasadas e tempo médio de atraso (considerando prazo alterado, troca de profissional, atraso em alteração e entrega de arquivos).",
    purpose: "Monitorar SLA operacional e riscos de entrega.",
    profiles: ["admin", "agency", "leader"],
    category: "tasks",
    visualType: ["kpi_alert", "bar_chart"],
    allowedScopes: ["GLOBAL", "OWN_AGENCY_SCOPE", "OWN_LEADER_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: true,
    dependencies: ["ProjectTask"],
    dataAvailability: "partial",
    missingFields: [
      "Não há campo is_late ou late_at — deve ser calculado em runtime: due_date < now() AND status NOT IN ('CONCLUIDA','CANCELADA')",
      "Atraso em 'alteração solicitada' não tem evento próprio no schema atual",
      "Atraso em 'arquivos finais' não tem evento próprio no schema atual",
    ],
    notes: "Cálculo básico: ProjectTask.due_date < now() AND status NOT final. Para rastreamento detalhado de motivo de atraso, adicionar tabela TaskDelayEvent.",
  },

  // ── 24. Pontuação de Tarefas ─────────────────────────────────────────────────
  {
    id: "pontuacao_tarefas",
    name: "Pontuação de Tarefas",
    description: "Média de avaliação das tarefas entregues no período. Filtrável por categoria.",
    purpose: "Medir qualidade de entrega e identificar categorias problemáticas.",
    profiles: ["admin", "agency", "nomad", "leader"],
    category: "tasks",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL", "OWN_AGENCY_SCOPE", "OWN_NOMAD_SCOPE", "OWN_LEADER_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: true,
    dependencies: ["TaskExecution"],
    dataAvailability: "available",
    notes: "AVG(TaskExecution.rating) onde status='approved'. Filtro por TaskExecution.template_id → TaskTemplate.category.",
  },

  // ── 25. Remuneração Nômade ────────────────────────────────────────────────────
  {
    id: "remuneracao_nomade",
    name: "Remuneração Nômade",
    description: "Total pago aos nômades no período e crescimento. Filtrável por categoria.",
    purpose: "Monitorar custo de execução e avaliar saúde da base de profissionais.",
    profiles: ["admin"],
    category: "nomads",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: true,
    dependencies: ["WalletTransaction", "Nomade"],
    dataAvailability: "available",
    notes: "Σ(WalletTransaction.amount WHERE type='credit' AND date no período) agrupado por Nomade. Filtro de categoria requer cruzar com tarefas do nômade.",
  },

  // ── 26. Remuneração Média ─────────────────────────────────────────────────────
  {
    id: "remuneracao_media",
    name: "Remuneração Média",
    description: "Total pago dividido pelo número de nômades que receberam tarefas no período.",
    purpose: "Avaliar distribuição de renda entre os profissionais ativos.",
    profiles: ["admin"],
    category: "nomads",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["WalletTransaction", "Nomade"],
    dataAvailability: "available",
    notes: "Derivado: Remuneração Total / COUNT(DISTINCT nomade_id com crédito no período).",
  },

  // ── 27. Clientes Ativos ───────────────────────────────────────────────────────
  {
    id: "clientes_ativos",
    name: "Clientes Ativos",
    description: "Agências com plano mensal ativo: total, novos clientes e crescimento.",
    purpose: "Medir base de clientes pagantes recorrentes.",
    profiles: ["admin"],
    category: "clients",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["Agency", "Project"],
    dataAvailability: "available",
    notes: "Agency.status='ativo' com pelo menos um Project.lifecycle='mensal' ativo. Novos = Agency.created_at no período.",
  },

  // ── 28. Clientes Outros Status ────────────────────────────────────────────────
  {
    id: "clientes_status",
    name: "Clientes — Outros Status",
    description: "Lista de clientes agrupados por status com comparação de período.",
    purpose: "Visão geral do estado da base de clientes.",
    profiles: ["admin"],
    category: "clients",
    visualType: ["donut_chart", "drill_list"],
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["Agency"],
    dataAvailability: "available",
    notes: "GROUP BY Agency.status. Status disponíveis: ativo | inativo | etc.",
  },

  // ── 29. Atividade ─────────────────────────────────────────────────────────────
  {
    id: "atividade",
    name: "Atividade",
    description: "Quantidade e percentual de agências que acessaram a plataforma no período. Permite abrir lista.",
    purpose: "Medir engajamento e uso da plataforma.",
    profiles: ["admin"],
    category: "activity",
    visualType: ["kpi_comparison", "drill_list"],
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["User", "Agency"],
    dataAvailability: "partial",
    missingFields: [
      "User.last_login armazena apenas o último login — não conta quantas vezes a agência acessou no período",
      "Não há tabela de sessões/logs de acesso por período",
    ],
    notes: "Pode-se usar User.last_login BETWEEN período para inferir atividade recente. Para contagem precisa de sessões, adicionar tabela UserSession ou UserActivityLog.",
  },

  // ── 30. Inatividade ───────────────────────────────────────────────────────────
  {
    id: "inatividade",
    name: "Inatividade",
    description: "Agências sem acesso há mais de 3 meses, com percentual sobre base ativa.",
    purpose: "Identificar clientes em risco de churn por falta de engajamento.",
    profiles: ["admin"],
    category: "activity",
    visualType: ["kpi_alert", "drill_list"],
    allowedScopes: ["GLOBAL"],
    allowsComparison: false,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["User", "Agency"],
    dataAvailability: "available",
    notes: "User.last_login < NOW() - 90 days para usuários de agências ativas. Agrupar por Agency.",
  },

  // ── 31. Tempo Médio de Uso ────────────────────────────────────────────────────
  {
    id: "tempo_medio_uso",
    name: "Tempo Médio de Uso",
    description: "Tempo médio diário das agências ativas na plataforma.",
    purpose: "Medir profundidade de engajamento além do simples login.",
    profiles: ["admin"],
    category: "activity",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["User"],
    dataAvailability: "missing",
    missingFields: [
      "Nenhum modelo de sessão com duração existe no schema",
      "Requer integração com analytics (ex.: Mixpanel, PostHog, ou tabela UserSession própria)",
    ],
    notes: "Implementar após decidir estratégia de analytics. Sugestão: tabela UserSession { user_id, started_at, ended_at, pages_visited }.",
  },

  // ── 32. Leads ──────────────────────────────────────────────────────────────────
  {
    id: "leads",
    name: "Leads",
    description: "Total de leads no período, crescimento e distribuição por status.",
    purpose: "Medir volume e qualidade do funil de aquisição.",
    profiles: ["admin", "agency"],
    category: "leads",
    visualType: ["kpi_comparison", "donut_chart"],
    allowedScopes: ["GLOBAL", "OWN_AGENCY_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: [],
    dataAvailability: "missing",
    missingFields: [
      "Nenhum modelo Lead existe no schema Prisma",
      "Necessário criar: Lead { id, name, email, phone, agency_id, status, source, value, created_at, converted_at, lost_at }",
      "Campos sugeridos de status: novo | em_atendimento | proposta_enviada | negociacao | convertido | perdido",
    ],
    notes: "Funcionalidade de CRM/leads é o principal gap para o funil comercial. Depende de nova migration.",
  },

  // ── 33. Convertidos ───────────────────────────────────────────────────────────
  {
    id: "convertidos",
    name: "Convertidos",
    description: "Leads que viraram projetos: percentual de conversão, valor total, tempo médio até fechamento.",
    purpose: "Medir eficiência do processo comercial.",
    profiles: ["admin", "agency"],
    category: "leads",
    visualType: "kpi_comparison",
    allowedScopes: ["GLOBAL", "OWN_AGENCY_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: [],
    dataAvailability: "missing",
    missingFields: ["Depende do modelo Lead — mesma ausência do indicador #32"],
    notes: "Lead.status='convertido' + Lead.converted_at + FK para Project.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// ADMIN — TABULAR REPORTS
// ═══════════════════════════════════════════════════════════════════════════════

export const ADMIN_TABULAR_REPORTS: TabularReportDefinition[] = [
  {
    id: "extrato_geral",
    name: "Extrato Geral",
    description: "Toda movimentação financeira da plataforma por período, com saldo diário por tipo de carteira.",
    profiles: ["admin"],
    category: "financial",
    columns: [
      { key: "date", label: "Data", type: "date", sortable: true },
      { key: "code", label: "Código", type: "text" },
      { key: "transaction_type", label: "Tipo", type: "badge", filterable: true },
      { key: "description", label: "Descrição", type: "text" },
      { key: "amount", label: "Valor", type: "currency", sortable: true },
      { key: "direction", label: "Entrada/Saída", type: "badge" },
      { key: "balance_after", label: "Saldo", type: "currency" },
      { key: "wallet_type", label: "Carteira", type: "badge", filterable: true },
    ],
    allowsExport: true,
    exportFormats: ["PDF", "XLSX"],
    allowsFilter: true,
    dependencies: ["WalletLedger", "Wallet"],
    dataAvailability: "available",
    notes: "WalletLedger tem todos os campos necessários: type, direction, amount, balance_after, description, reference_type, reference_id.",
  },

  {
    id: "relatorio_projetos",
    name: "Projetos",
    description: "Todos os projetos com datas, status, valores, agências e dados relacionados.",
    profiles: ["admin"],
    category: "projects",
    columns: [
      { key: "id", label: "Código", type: "text" },
      { key: "title", label: "Projeto", type: "text", sortable: true },
      { key: "value_avulso", label: "Valor Avulso", type: "currency" },
      { key: "value_mensal", label: "Valor Mensal", type: "currency" },
      { key: "status", label: "Status", type: "badge", filterable: true },
      { key: "agency", label: "Agência", type: "text", filterable: true },
      { key: "partner", label: "Embaixadora/Parceira", type: "text" },
      { key: "created_at", label: "Data de Abertura", type: "date", sortable: true },
      { key: "cancelled_at", label: "Data de Cancelamento", type: "date", hiddenByDefault: true },
      { key: "updated_at", label: "Última Alteração", type: "date" },
      { key: "avg_rating", label: "Pontuação Média", type: "number" },
    ],
    allowsExport: true,
    exportFormats: ["PDF", "XLSX"],
    allowsFilter: true,
    dependencies: ["Project", "Invoice", "AgencyLeadership", "PartnerProfile"],
    dataAvailability: "partial",
    missingFields: [
      "Project.agency é string (não FK) — filtro por agência é textual",
      "Campo partner/embaixadora não existe diretamente em Project — requer JOIN via Agency → AgencyLeadership → PartnerProfile",
      "Pontuação média do produto não está em Project — requer derivação de TaskExecution.rating dos produtos do projeto",
    ],
  },

  {
    id: "relatorio_agencias",
    name: "Agências",
    description: "Lista completa de agências com contratações, projetos, leads e LTV.",
    profiles: ["admin"],
    category: "clients",
    columns: [
      { key: "id", label: "ID", type: "text" },
      { key: "name", label: "Agência", type: "text", sortable: true },
      { key: "master_user", label: "Usuário Master", type: "text" },
      { key: "partner", label: "Embaixadora/Parceira", type: "text" },
      { key: "status", label: "Status", type: "badge", filterable: true },
      { key: "plan", label: "Plano Contratado", type: "text" },
      { key: "created_at", label: "Data de Cadastro", type: "date", sortable: true },
      { key: "last_payment", label: "Último Pagamento", type: "date" },
      { key: "last_login", label: "Último Acesso", type: "date" },
      { key: "period_revenue", label: "Contratação no Período", type: "currency" },
      { key: "ltv_revenue", label: "Contratação LTV", type: "currency" },
      { key: "monthly_revenue", label: "Contratação Mensal", type: "currency" },
      { key: "avulso_revenue", label: "Contratação Avulsa", type: "currency" },
      { key: "last_contract", label: "Última Contratação", type: "date" },
      { key: "active_projects", label: "Projetos Ativos", type: "number" },
      { key: "cancelled_projects", label: "Projetos Cancelados", type: "number" },
      { key: "draft_projects", label: "Projetos Rascunho", type: "number" },
      { key: "leads_received", label: "Leads Recebidos", type: "number", hiddenByDefault: true },
      { key: "leads_lost", label: "Leads Perdidos", type: "number", hiddenByDefault: true },
      { key: "leads_converted", label: "Leads Convertidos", type: "number", hiddenByDefault: true },
      { key: "lead_revenue", label: "Contratação por Lead", type: "currency", hiddenByDefault: true },
    ],
    allowsExport: true,
    exportFormats: ["PDF", "XLSX"],
    allowsFilter: true,
    dependencies: ["Agency", "User", "Project", "Invoice", "AgencyLeadership", "SquadConfig"],
    dataAvailability: "partial",
    missingFields: [
      "Colunas de lead requerem modelo Lead inexistente",
      "Contratação LTV requer aggregação histórica de Invoice por agência via Project.agency (string)",
      "Plano contratado requer SquadConfig vinculado à agência — Agency não tem FK direto para SquadConfig",
    ],
  },

  {
    id: "relatorio_leads",
    name: "Leads",
    description: "Lista de leads com percurso completo e resultados de conversão.",
    profiles: ["admin", "agency"],
    category: "leads",
    columns: [
      { key: "id", label: "ID", type: "text" },
      { key: "name", label: "Lead", type: "text" },
      { key: "status", label: "Status Atual", type: "badge", filterable: true },
      { key: "created_at", label: "Data de Entrada", type: "date" },
      { key: "time_to_first_contact", label: "Tempo até Atendimento", type: "duration" },
      { key: "report_count", label: "Qtd. de Reports", type: "number" },
      { key: "time_to_conversion", label: "Tempo até Conversão", type: "duration" },
      { key: "time_to_lost", label: "Tempo até Perdido", type: "duration" },
      { key: "proposal_value", label: "Valor da Proposta", type: "currency" },
      { key: "proposal_value_no_margin", label: "Valor sem Margem", type: "currency" },
      { key: "proposal_status", label: "Status da Proposta", type: "badge" },
      { key: "billed_value", label: "Valor Faturado", type: "currency" },
    ],
    allowsExport: true,
    exportFormats: ["PDF", "XLSX"],
    allowsFilter: true,
    dependencies: [],
    dataAvailability: "missing",
    missingFields: ["Modelo Lead inexistente — relatório completo impossível sem nova migration"],
  },

  {
    id: "relatorio_nomades",
    name: "Nômades",
    description: "Lista completa de nômades com desempenho, tarefas e remuneração por período.",
    profiles: ["admin"],
    category: "nomads",
    columns: [
      { key: "id", label: "ID", type: "text" },
      { key: "name", label: "Nômade", type: "text", sortable: true },
      { key: "status", label: "Status", type: "badge", filterable: true },
      { key: "level", label: "Nível", type: "badge", filterable: true },
      { key: "registration_date", label: "Data de Cadastro", type: "date", sortable: true },
      { key: "first_task_date", label: "Primeira Tarefa", type: "date" },
      { key: "last_access", label: "Último Acesso", type: "date" },
      { key: "period_tasks", label: "Tarefas no Período", type: "number" },
      { key: "period_revenue", label: "Valor Recebido no Período", type: "currency" },
      { key: "total_tasks", label: "Total de Tarefas", type: "number" },
      { key: "total_revenue", label: "Valor Total Recebido", type: "currency" },
      { key: "ticket_medio", label: "Ticket Médio", type: "currency" },
      { key: "active_tasks", label: "Em Andamento", type: "number" },
      { key: "rejected_tasks", label: "Rejeitadas", type: "number" },
      { key: "late_tasks", label: "Perdidas/Atrasadas", type: "number" },
      { key: "penalties", label: "Multas", type: "currency" },
      { key: "avg_rejection", label: "Média de Reprovação", type: "percentage" },
      { key: "current_score", label: "Pontuação Atual", type: "number" },
      { key: "period_score", label: "Pontuação do Período", type: "number", hiddenByDefault: true },
    ],
    allowsExport: true,
    exportFormats: ["PDF", "XLSX"],
    allowsFilter: true,
    dependencies: ["Nomade", "ProjectTask", "TaskExecution", "WalletTransaction"],
    dataAvailability: "partial",
    missingFields: [
      "Nomade.last_access não existe — Nomade tem created_at mas não last_access (User.last_login pode suprir se user_id vinculado)",
      "first_task_date requer MIN(ProjectTask.created_at) por nômade",
      "period_score requer snapshot histórico — atualmente só o score atual é armazenado",
      "Penalidades requerem WalletTransaction.type='penalty' — existe no schema",
    ],
  },

  {
    id: "relatorio_usabilidade",
    name: "Usabilidade",
    description: "MAU, DAU, acessos por tela, abandono de fluxos chave da plataforma.",
    profiles: ["admin"],
    category: "activity",
    columns: [
      { key: "metric", label: "Métrica", type: "text" },
      { key: "value", label: "Valor", type: "number" },
      { key: "previous", label: "Período Anterior", type: "number" },
      { key: "delta", label: "Variação", type: "percentage" },
    ],
    allowsExport: true,
    exportFormats: ["PDF", "XLSX"],
    allowsFilter: false,
    dependencies: [],
    dataAvailability: "missing",
    missingFields: [
      "MAU/DAU requerem rastreamento de sessões (modelo UserSession inexistente)",
      "Acessos por tela requerem instrumentação frontend (PostHog, Mixpanel ou evento customizado)",
      "Abandono de checkout/montagem de projeto requerem eventos de funil",
    ],
    notes: "Implementar após definir estratégia de produto analytics. Pode ser feito com PostHog self-hosted ou tabela UserPageView própria.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// AGENCY — INDICATORS
// ═══════════════════════════════════════════════════════════════════════════════

export const AGENCY_INDICATORS: IndicatorDefinition[] = [
  {
    id: "agency_projetos_status",
    name: "Projetos por Status",
    description: "Distribuição dos projetos da agência por status.",
    purpose: "Visão geral do pipeline de projetos da agência.",
    profiles: ["agency"],
    category: "projects",
    visualType: ["donut_chart", "kpi"],
    allowedScopes: ["OWN_AGENCY_SCOPE"],
    allowsComparison: false,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["Project"],
    dataAvailability: "partial",
    missingFields: ["Project não tem FK para Agency — vínculo é Project.agency (string)"],
    notes: "Filtrar Project.agency = Agency.name. Idealmente adicionar Project.agency_id (FK).",
  },
  {
    id: "agency_tarefas_status",
    name: "Tarefas por Status",
    description: "Distribuição das tarefas dos projetos da agência por status.",
    purpose: "Monitorar execução operacional.",
    profiles: ["agency"],
    category: "tasks",
    visualType: "donut_chart",
    allowedScopes: ["OWN_AGENCY_SCOPE"],
    allowsComparison: false,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["ProjectTask", "Project"],
    dataAvailability: "partial",
    missingFields: ["Herda limitação de Project → Agency sem FK direto"],
  },
  {
    id: "agency_clientes_ativos",
    name: "Clientes Ativos",
    description: "Empresas/clientes com projetos ativos na agência.",
    purpose: "Medir carteira de clientes.",
    profiles: ["agency"],
    category: "clients",
    visualType: "kpi",
    allowedScopes: ["OWN_AGENCY_SCOPE"],
    allowsComparison: false,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["Project", "Company"],
    dataAvailability: "partial",
    missingFields: ["Project.client_id FK para Company existe — viável após cruzar com agency"],
  },
  {
    id: "agency_contratacoes_recorrentes",
    name: "Contratações Recorrentes",
    description: "Valor de produtos mensais contratados pela agência no período.",
    purpose: "Medir MRR próprio da agência.",
    profiles: ["agency"],
    category: "financial",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_AGENCY_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["Project", "Invoice"],
    dataAvailability: "partial",
    missingFields: ["Herda limitação de Project.agency como string"],
  },
  {
    id: "agency_contratacoes_avulsas",
    name: "Contratações Avulsas",
    description: "Valor de produtos avulsos contratados pela agência no período.",
    purpose: "Medir receita não-recorrente gerada pela agência.",
    profiles: ["agency"],
    category: "financial",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_AGENCY_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["Project", "Invoice"],
    dataAvailability: "partial",
    missingFields: ["Herda limitação de Project.agency como string"],
  },
  {
    id: "agency_checkout_cliente",
    name: "Checkout do Cliente",
    description: "Total de projetos contratados via checkout do cliente pela agência.",
    purpose: "Medir efetividade do checkout direto.",
    profiles: ["agency"],
    category: "financial",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_AGENCY_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["Project"],
    dataAvailability: "partial",
    missingFields: ["Project.company_type='company' é o filtro disponível, mas herda limitação de agency_id"],
  },
  {
    id: "agency_churn_projetos",
    name: "Churn de Projetos",
    description: "Projetos recorrentes cancelados da agência no período.",
    purpose: "Monitorar perda de receita recorrente.",
    profiles: ["agency"],
    category: "financial",
    visualType: "kpi_alert",
    allowedScopes: ["OWN_AGENCY_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["Project"],
    dataAvailability: "partial",
    missingFields: ["Herda limitações do indicador churn_projetos Admin"],
  },
  {
    id: "agency_ticket_medio",
    name: "Ticket Médio",
    description: "Valor médio por contratação da agência no período.",
    purpose: "Avaliar evolução do ticket de vendas.",
    profiles: ["agency"],
    category: "financial",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_AGENCY_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["Invoice", "Project"],
    dataAvailability: "partial",
    missingFields: ["Herda limitação de Project.agency como string"],
  },
  {
    id: "agency_leads",
    name: "Leads",
    description: "Total de leads recebidos pela agência e taxa de conversão.",
    purpose: "Medir funil comercial da agência.",
    profiles: ["agency"],
    category: "leads",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_AGENCY_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: [],
    dataAvailability: "missing",
    missingFields: ["Modelo Lead inexistente"],
  },
  {
    id: "agency_pontuacao",
    name: "Pontuação da Agência",
    description: "Pontuação de desempenho da agência na plataforma.",
    purpose: "Medir qualidade e engajamento da agência.",
    profiles: ["agency"],
    category: "gamification",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_AGENCY_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["Agency", "AgencyReport"],
    dataAvailability: "partial",
    missingFields: [
      "Agency não tem campo score direto — AgencyReport.rating é por relatório mensal, não um score acumulado",
      "Sugestão: adicionar Agency.score ou calcular média de AgencyReport.rating",
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// PARTNER / EMBAIXADORA — INDICATORS
// ═══════════════════════════════════════════════════════════════════════════════
// Inclui todos os indicadores de Agency + visibilidade sobre agências lideradas

export const PARTNER_INDICATORS: IndicatorDefinition[] = [
  ...AGENCY_INDICATORS.map((ind) => ({
    ...ind,
    id: `partner_own_${ind.id}`,
    profiles: ["partner"] as ("partner")[],
    allowedScopes: ["OWN_PARTNER_SCOPE"] as ("OWN_PARTNER_SCOPE")[],
  })),
  {
    id: "partner_agencias_lideradas_status",
    name: "Agências Lideradas — Status",
    description: "Distribuição por status das agências sob liderança do parceiro.",
    purpose: "Visão geral da carteira de agências gerenciadas.",
    profiles: ["partner"],
    category: "partner_mgmt",
    visualType: ["donut_chart", "drill_list"],
    allowedScopes: ["OWN_PARTNER_SCOPE"],
    allowsComparison: false,
    allowsDrillDown: true,
    allowsExport: true,
    allowsFilter: false,
    dependencies: ["AgencyLeadership", "Agency"],
    dataAvailability: "available",
    notes: "AgencyLeadership.partner_id → Agency via agency_id. Clicar abre detalhe daquela agência.",
  },
  {
    id: "partner_projetos_agencias",
    name: "Projetos das Agências Lideradas",
    description: "Projetos por status de todas as agências sob liderança.",
    purpose: "Monitorar pipeline das agências gerenciadas.",
    profiles: ["partner"],
    category: "projects",
    visualType: "donut_chart",
    allowedScopes: ["OWN_PARTNER_SCOPE"],
    allowsComparison: false,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: true,
    dependencies: ["AgencyLeadership", "Agency", "Project"],
    dataAvailability: "partial",
    missingFields: ["Project.agency como string — mesma limitação de todas as consultas agency→project"],
  },
  {
    id: "partner_tarefas_agencias",
    name: "Tarefas das Agências Lideradas",
    description: "Tarefas por status de todas as agências sob liderança.",
    purpose: "Visão operacional consolidada das agências gerenciadas.",
    profiles: ["partner"],
    category: "tasks",
    visualType: "donut_chart",
    allowedScopes: ["OWN_PARTNER_SCOPE"],
    allowsComparison: false,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: true,
    dependencies: ["AgencyLeadership", "Agency", "ProjectTask"],
    dataAvailability: "partial",
    missingFields: ["Herda mesma limitação de agency → ProjectTask"],
  },
  {
    id: "partner_usabilidade_agencias",
    name: "Usabilidade das Agências Lideradas",
    description: "Último acesso e frequência de uso da plataforma pelas agências.",
    purpose: "Identificar agências em risco de desengajamento.",
    profiles: ["partner"],
    category: "activity",
    visualType: "drill_list",
    allowedScopes: ["OWN_PARTNER_SCOPE"],
    allowsComparison: false,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["AgencyLeadership", "User"],
    dataAvailability: "partial",
    missingFields: ["Mesmo gap de User.last_login vs. sessões do indicador de Atividade Admin"],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// NOMAD — INDICATORS
// ═══════════════════════════════════════════════════════════════════════════════

export const NOMAD_INDICATORS: IndicatorDefinition[] = [
  {
    id: "nomad_pontuacao",
    name: "Pontuação",
    description: "Pontuação atual e histórico de evolução do nômade.",
    purpose: "Acompanhar progressão na gamificação.",
    profiles: ["nomad"],
    category: "gamification",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_NOMAD_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["Nomade"],
    dataAvailability: "partial",
    missingFields: ["Histórico de pontuação não existe — só score atual em Nomade.score"],
    notes: "Score atual disponível. Para evolução temporal, adicionar tabela NomadeScoreHistory.",
  },
  {
    id: "nomad_tarefas_recebidas",
    name: "Tarefas Recebidas",
    description: "Tarefas recebidas pelo nômade no período.",
    purpose: "Monitorar volume de trabalho.",
    profiles: ["nomad"],
    category: "tasks",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_NOMAD_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["ProjectTask"],
    dataAvailability: "available",
    notes: "COUNT(ProjectTask WHERE nomade_responsavel_id = current_nomade.id).",
  },
  {
    id: "nomad_tarefas_concluidas",
    name: "Tarefas Concluídas",
    description: "Tarefas concluídas pelo nômade no período.",
    purpose: "Medir produtividade.",
    profiles: ["nomad"],
    category: "tasks",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_NOMAD_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["ProjectTask"],
    dataAvailability: "available",
    notes: "ProjectTask.status='CONCLUIDA' + nomade_responsavel_id.",
  },
  {
    id: "nomad_tarefas_atrasadas",
    name: "Tarefas Atrasadas",
    description: "Tarefas com prazo vencido ainda em aberto.",
    purpose: "Auto-monitoramento de SLA.",
    profiles: ["nomad"],
    category: "tasks",
    visualType: "kpi_alert",
    allowedScopes: ["OWN_NOMAD_SCOPE"],
    allowsComparison: false,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["ProjectTask"],
    dataAvailability: "partial",
    missingFields: ["Mesma limitação do indicador tarefas_atrasadas Admin"],
  },
  {
    id: "nomad_tarefas_reprovadas",
    name: "Tarefas Reprovadas",
    description: "Tarefas reprovadas/rejeitadas no período.",
    purpose: "Monitorar qualidade de entrega.",
    profiles: ["nomad"],
    category: "tasks",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_NOMAD_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["TaskExecution"],
    dataAvailability: "available",
    notes: "TaskExecution.status='rejected'.",
  },
  {
    id: "nomad_pontuacao_tarefas",
    name: "Pontuação de Tarefas",
    description: "Média de avaliação das tarefas entregues pelo nômade.",
    purpose: "Auto-avaliação de qualidade.",
    profiles: ["nomad"],
    category: "tasks",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_NOMAD_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["TaskExecution"],
    dataAvailability: "available",
    notes: "AVG(TaskExecution.rating) WHERE nomade_id = current.",
  },
  {
    id: "nomad_remuneracao",
    name: "Remuneração",
    description: "Valor recebido pelo nômade no período.",
    purpose: "Acompanhar ganhos.",
    profiles: ["nomad"],
    category: "financial",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_NOMAD_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["WalletTransaction"],
    dataAvailability: "available",
    notes: "WalletTransaction.type='credit' WHERE nomade_id = current.",
  },
  {
    id: "nomad_comissoes",
    name: "Comissões",
    description: "Comissões recebidas pelo nômade (bonus por performance, etc.).",
    purpose: "Transparência sobre bônus e comissões.",
    profiles: ["nomad"],
    category: "financial",
    visualType: "kpi",
    allowedScopes: ["OWN_NOMAD_SCOPE"],
    allowsComparison: false,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["WalletTransaction"],
    dataAvailability: "partial",
    missingFields: [
      "WalletTransaction.type='bonus' existe, mas não há distinção clara entre bonus de comissão e outros bônus",
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// LEADER — INDICATORS
// ═══════════════════════════════════════════════════════════════════════════════

export const LEADER_INDICATORS: IndicatorDefinition[] = [
  {
    id: "leader_pontuacao",
    name: "Pontuação do Líder",
    description: "Pontuação atual do líder na plataforma.",
    purpose: "Acompanhar desempenho geral.",
    profiles: ["leader"],
    category: "gamification",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_LEADER_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["Nomade"],
    dataAvailability: "partial",
    missingFields: ["Líderes são nômades com Nomade.is_leader=true — score disponível via Nomade.score"],
    notes: "Nomade WHERE is_leader=true AND user_id = current user.",
  },
  {
    id: "leader_tarefas_recebidas",
    name: "Tarefas Recebidas",
    description: "Tarefas recebidas para execução e para liderança no período.",
    purpose: "Monitorar volume de trabalho próprio e de liderança.",
    profiles: ["leader"],
    category: "tasks",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_LEADER_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["ProjectTask"],
    dataAvailability: "available",
    notes: "ProjectTask WHERE nomade_responsavel_id = líder (execução própria) OR lider_responsavel_id = líder (liderança).",
  },
  {
    id: "leader_tarefas_concluidas",
    name: "Tarefas Concluídas",
    description: "Tarefas concluídas pelo líder ou sob sua liderança.",
    purpose: "Medir produtividade total gerenciada.",
    profiles: ["leader"],
    category: "tasks",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_LEADER_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["ProjectTask"],
    dataAvailability: "available",
    notes: "ProjectTask.status='CONCLUIDA' WHERE lider_responsavel_id = líder.",
  },
  {
    id: "leader_tarefas_atrasadas",
    name: "Tarefas Atrasadas",
    description: "Tarefas em atraso sob sua liderança.",
    purpose: "Gestão de SLA da equipe.",
    profiles: ["leader"],
    category: "tasks",
    visualType: "kpi_alert",
    allowedScopes: ["OWN_LEADER_SCOPE"],
    allowsComparison: false,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["ProjectTask"],
    dataAvailability: "partial",
    missingFields: ["Mesma limitação do indicador tarefas_atrasadas"],
  },
  {
    id: "leader_tarefas_reprovadas",
    name: "Tarefas Reprovadas",
    description: "Tarefas reprovadas sob liderança no período.",
    purpose: "Monitorar qualidade da equipe.",
    profiles: ["leader"],
    category: "tasks",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_LEADER_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["TaskExecution"],
    dataAvailability: "available",
    notes: "TaskExecution.status='rejected' para tarefas do líder ou nômades sob sua liderança.",
  },
  {
    id: "leader_pontuacao_tarefas",
    name: "Pontuação de Tarefas",
    description: "Média de avaliação das tarefas entregues sob liderança.",
    purpose: "Medir qualidade da equipe gerenciada.",
    profiles: ["leader"],
    category: "tasks",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_LEADER_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["TaskExecution"],
    dataAvailability: "available",
  },
  {
    id: "leader_remuneracao",
    name: "Remuneração",
    description: "Valor recebido pelo líder por tarefas de liderança no período.",
    purpose: "Acompanhar ganhos relacionados à liderança.",
    profiles: ["leader"],
    category: "financial",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_LEADER_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["WalletTransaction"],
    dataAvailability: "partial",
    missingFields: [
      "WalletTransaction não distingue pagamento de 'execução' vs. 'liderança' — não há campo task_role",
    ],
  },
  {
    id: "leader_comissoes",
    name: "Comissões",
    description: "Comissões recebidas pelo líder.",
    purpose: "Transparência sobre incentivos de liderança.",
    profiles: ["leader"],
    category: "financial",
    visualType: "kpi",
    allowedScopes: ["OWN_LEADER_SCOPE"],
    allowsComparison: false,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["WalletTransaction"],
    dataAvailability: "partial",
    missingFields: ["Mesma limitação do indicador nomad_comissoes"],
  },
  {
    id: "leader_faturamento_proporcionado",
    name: "Faturamento Proporcionado",
    description: "Faturamento gerado pelos projetos que passaram por tarefas sob a liderança.",
    purpose: "Demonstrar impacto da liderança na receita.",
    profiles: ["leader"],
    category: "financial",
    visualType: "kpi_comparison",
    allowedScopes: ["OWN_LEADER_SCOPE"],
    allowsComparison: true,
    allowsDrillDown: false,
    allowsExport: false,
    allowsFilter: false,
    dependencies: ["ProjectTask", "Project", "Invoice"],
    dataAvailability: "partial",
    missingFields: [
      "Requer derivação: ProjectTask(lider_responsavel_id) → project_id → Invoice.amount",
      "Atribuição de faturamento por líder é uma divisão proporcional que não tem campo próprio",
    ],
  },
  {
    id: "leader_nomades_drill",
    name: "Desempenho por Nômade",
    description: "Clicar num nômade habilitado mostra desempenho por tarefa específica.",
    purpose: "Gestão granular de profissionais da equipe.",
    profiles: ["leader"],
    category: "nomads",
    visualType: "drill_list",
    allowedScopes: ["OWN_LEADER_SCOPE"],
    allowsComparison: false,
    allowsDrillDown: true,
    allowsExport: false,
    allowsFilter: true,
    dependencies: ["LiderArea", "Nomade", "ProjectTask", "TaskExecution"],
    dataAvailability: "partial",
    missingFields: [
      "LiderArea.categorias_permitidas define categorias mas não mapeia nômades diretamente ao líder",
      "Requer lógica: encontrar nômades que executaram tarefas nas categorias habilitadas do líder",
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// COMBINED EXPORTS
// ═══════════════════════════════════════════════════════════════════════════════

export const ALL_KPI_INDICATORS: IndicatorDefinition[] = [
  ...ADMIN_INDICATORS,
  ...AGENCY_INDICATORS,
  ...PARTNER_INDICATORS,
  ...NOMAD_INDICATORS,
  ...LEADER_INDICATORS,
];

export const ALL_TABULAR_REPORTS: TabularReportDefinition[] = [
  ...ADMIN_TABULAR_REPORTS,
];

/** Flat indexed map by indicator id for O(1) lookup */
export const INDICATOR_BY_ID = Object.fromEntries(
  ALL_KPI_INDICATORS.map((i) => [i.id, i]),
) as Record<string, IndicatorDefinition>;

/** Data availability summary — useful for dev dashboard / status page */
export const DATA_AVAILABILITY_SUMMARY = {
  indicators: {
    available: ALL_KPI_INDICATORS.filter((i) => i.dataAvailability === "available").length,
    partial:   ALL_KPI_INDICATORS.filter((i) => i.dataAvailability === "partial").length,
    missing:   ALL_KPI_INDICATORS.filter((i) => i.dataAvailability === "missing").length,
  },
  reports: {
    available: ALL_TABULAR_REPORTS.filter((r) => r.dataAvailability === "available").length,
    partial:   ALL_TABULAR_REPORTS.filter((r) => r.dataAvailability === "partial").length,
    missing:   ALL_TABULAR_REPORTS.filter((r) => r.dataAvailability === "missing").length,
  },
} as const;
