param()
$f = Join-Path $PSScriptRoot "app\admin\modelos-tarefas\page.tsx"
$c = [System.IO.File]::ReadAllText($f, [System.Text.Encoding]::UTF8)
$r = [char]0xFFFD

function R($s, $from, $to) { return $s.Replace($from, $to) }

# Fix all corrupted Portuguese characters
# Each U+FFFD was originally a single accented character

$c = R $c "Em Revis${r}o" "Em Revisão"
$c = R $c "Execu${r}${r}o" "Execução"
$c = R $c "Aprova${r}${r}o" "Aprovação"
$c = R $c "Qualifica${r}${r}o" "Qualificação"
$c = R $c "Intermedi${r}ria" "Intermediária"
$c = R $c "Avan${r}ada" "Avançada"
$c = R $c "B${r}sica" "Básica"
$c = R $c "M${r}dia" "Média"
$c = R $c "Prazo padr${r}o" "Prazo padrão"
$c = R $c "Checklist padr${r}o" "Checklist padrão"
$c = R $c "Restaurar padr${r}o" "Restaurar padrão"
$c = R $c "padr${r}o" "padrão"
$c = R $c "Vis${r}o Geral" "Visão Geral"
$c = R $c "vis${r}o" "visão"
$c = R $c "Descri${r}${r}o" "Descrição"
$c = R $c "descri${r}${r}o" "descrição"
$c = R $c "Orienta${r}${r}o" "Orientação"
$c = R $c "orienta${r}${r}o" "orientação"
$c = R $c "Observa${r}${r}es" "Observações"
$c = R $c "observa${r}${r}es" "observações"
$c = R $c "Etapas de execu${r}${r}o" "Etapas de execução"
$c = R $c "Regras de execu${r}${r}o" "Regras de execução"
$c = R $c "Regras de conclus${r}o" "Regras de conclusão"
$c = R $c "execu${r}${r}o" "execução"
$c = R $c "conclus${r}o" "conclusão"
$c = R $c "Arquivos necess${r}rios" "Arquivos necessários"
$c = R $c "necess${r}rios" "necessários"
$c = R $c "Obrigat${r}ria" "Obrigatória"
$c = R $c "obrigat${r}ria" "obrigatória"
$c = R $c "Revis${r}o" "Revisão"
$c = R $c "revis${r}o" "revisão"
$c = R $c "C${r}digo" "Código"
$c = R $c "c${r}digo" "código"
$c = R $c "c${r}pia" "cópia"
$c = R $c "reutiliz${r}veis" "reutilizáveis"
$c = R $c "reutiliz${r}vel" "reutilizável"
$c = R $c "N${r}o foi poss${r}vel" "Não foi possível"
$c = R $c "poss${r}vel" "possível"
$c = R $c "N${r}o vinculado" "Não vinculado"
$c = R $c "n${r}o est${r}" "não está"
$c = R $c "n${r}o" "não"
$c = R $c "N${r}o" "Não"
$c = R $c "est${r} " "está "
$c = R $c "impactar${r}o" "impactarão"
$c = R $c "Altera${r}${r}es" "Alterações"
$c = R $c "altera${r}${r}es" "alterações"
$c = R $c "Vincula${r}${r}o" "Vinculação"
$c = R $c "vincula${r}${r}o" "vinculação"
$c = R $c "Vincula${r}${r}es" "Vinculações"
$c = R $c "vincula${r}${r}es" "vinculações"
$c = R $c "Filtros avan${r}ados" "Filtros avançados"
$c = R $c "avan${r}ado" "avançado"
$c = R $c "Avan${r}ado" "Avançado"
$c = R $c " Avan${r}" " Avançado"
$c = R $c "Criado at${r}" "Criado até"
$c = R $c "Atualizado at${r}" "Atualizado até"
$c = R $c "m${r}nima" "mínima"
$c = R $c "Colunas vis${r}veis" "Colunas visíveis"
$c = R $c "prefer${r}ncia" "preferência"
$c = R $c "Prefer${r}ncia" "Preferência"
$c = R $c "salva automaticamente" "salva automaticamente"
$c = R $c "Carregando modelos de tarefas${r}" "Carregando modelos de tarefas…"
$c = R $c "Modelos de tarefas s${r}o" "Modelos de tarefas são"
$c = R $c "para come${r}ar" "para começar"
$c = R $c "A${r}${r}es" "Ações"
$c = R $c "a${r}${r}es" "ações"
$c = R $c "a${r}${r}o" "ação"
$c = R $c "Enviar p/ revis${r}o" "Enviar p/ revisão"
$c = R $c "P${r}gina" "Página"
$c = R $c "p${r}gina" "página"
$c = R $c "Crie um modelo reutiliz${r}vel" "Crie um modelo reutilizável"
$c = R $c "poder${r} ser" "poderá ser"
$c = R $c "autom${r}ticamente" "automaticamente"
$c = R $c "Configura${r}${r}o de Tag Manager" "Configuração de Tag Manager"
$c = R $c "Tr${r}fego Pago" "Tráfego Pago"
$c = R $c "Em revis${r}o" "Em revisão"
$c = R $c "em revis${r}o" "em revisão"
$c = R $c "Ap${r}s valida${r}${r}o" "Após validação"
$c = R $c "Ap${r}s" "Após"
$c = R $c "valida${r}${r}o" "validação"
$c = R $c "Gerencie modelos reutiliz${r}veis" "Gerencie modelos reutilizáveis"
$c = R $c "Salvando${r}" "Salvando…"
$c = R $c "return `"${r}`"" 'return "—"'
$c = R $c " ${r} " " · "
$c = R $c "`"${r}`"" '"›"'
$c = R $c "· P${r}gina" "· Página"
$c = R $c "· filtros ativos" "· filtros ativos"
$c = R $c "Buscar por c${r}digo" "Buscar por código"
$c = R $c "Gerencie.*reutiliz${r}veis" ""

# Count remaining
$remaining = ($c.ToCharArray() | Where-Object {[int]$_ -eq 0xFFFD}).Count
Write-Host "Remaining FFFD: $remaining"

# Write file
$enc = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($f, $c, $enc)
Write-Host "Done"
