// Ajuda por campo (2026-10-06): cada campo/legenda do editor de produto ganha um ícone "i"; ao passar o mouse mostra exatamente o que é o campo.
// O texto é procurado pelo nome do campo (sem acento/maiúscula; ignora ":", "*", "(opcional)" e o que vem depois de " — ").

export const normalizeHelpKey = (raw: string): string =>
  raw.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/\s+/g, " ").replace(/[:*]+\s*$/g, "").trim();

const H: Record<string, string> = {
  // ── Informações do produto
  "titulo comercial": "O nome do produto como o cliente vê. É também o nome do produto no sistema (não existe mais um nome interno separado).",
  "descricao curta": "Resumo de uma ou duas frases que aparece no card e na lista do catálogo. Até 500 caracteres.",
  "descricao": "Explicação completa do produto: o que é, como funciona, benefícios e diferenciais. É o texto principal da página do produto para o cliente.",
  "pilar": "Grande área do negócio em que o produto se encaixa (usada para organizar e filtrar o catálogo).",
  "categoria": "Subgrupo dentro do pilar. Ajuda o cliente a encontrar o produto e também alimenta o rodízio de nômades por área.",
  "classificacoes 4f": "As classificações 4F do produto (até 4). São usadas para filtrar e agrupar produtos no catálogo.",
  "quem pode ver este produto": "Define para quais públicos o produto aparece e pode ser contratado: todos, só Company, só Agency (comum), só Agency Partner, ou só equipe interna. Valem lista, detalhe, cotação, cesta e a IA.",
  "company": "Empresas (contas company). Marque para o produto aparecer para elas.",
  "agency (sem partner)": "Somente agências comuns. As agências partner NÃO veem este produto (marque também Agency Partner para incluí-las).",
  "agency partner": "Somente agências partner ativas.",
  "somente equipe interna": "Só administração e líderes veem o produto. Desmarca as outras opções.",
  "horas a reduzir": "Quantas horas esta etapa encurta quando o cliente escolhe a entrega emergencial. Não pode passar do tempo da própria etapa.",
  "adicional": "Quanto se cobra a mais por esta etapa na entrega emergencial: valor fixo em reais ou percentual do preço da etapa.",
  "valor": "Valor do adicional (R$ ou %, conforme o tipo escolhido).",
  "niveis de agencia": "Limita o produto a certos níveis de agência (os níveis cadastrados em Administração > Níveis Agências; se cadastrar um novo, ele aparece aqui). Só vale para agências: empresas e equipe interna continuam vendo. Todos marcados = sem restrição.",
  "todos os niveis": "Sem restrição por nível: agências de qualquer nível enxergam o produto (respeitando o público escolhido acima).",
  "passa pela qualificacao do especialista": "Opção separada da do líder: depois da entrega (e da qualificação do líder, se houver), o especialista escolhido confere o trabalho. Só ele (ou a administração) decide.",
  "quem aprova esta etapa": "Quem confere a entrega da etapa antes de ela seguir: o líder, o especialista, ou o líder e depois o especialista. Quando a etapa é feita por IA (ou híbrida), SEMPRE precisa de um qualificador aprovando.",
  "alteracoes por ia gratis neste produto": "Quantas alterações por IA o cliente faz sem pagar em cada contratação deste produto. Vazio = regra global (Configurações). Depois das grátis, cada alteração é cobrada do saldo da carteira.",
  "especialista que qualifica":"Quem confere a etapa como especialista: líder, administrador ou nômade ativo. Obrigatório quando a qualificação do especialista está ligada.",
  "todos": "Marque para o produto aparecer para qualquer cliente (empresas e agências). Marcar uma opção específica desmarca esta.",
  "informacoes comerciais": "Textos de venda do produto: resumo, descrição, o que está incluído e o que não está.",
  "base comercial": "Dados de venda deste produto: prazo, modalidades e implementação.",
  // ── Entrega comercial
  "prazo comercial base": "Prazo prometido ao cliente, informado em HORAS. O campo ao lado mostra o reflexo em dias (24 h = 1 dia; 5 h = 0,21 dia). O sistema guarda o dia inteiro arredondado para cima (mínimo 1). Variações, adicionais e condições podem somar a ele.",
  "tipo de preco": "Como o preço é definido: calculado pelas tarefas (custo + taxas), preço fixo informado por você, ou sob consulta.",
  "implementacao roda": "Quando a implementação inicial (configuração/onboarding) é executada: na primeira contratação do cliente, em toda contratação, ou conforme a regra escolhida.",
  "modalidades de contratacao": "Como o cliente pode comprar: Avulso (compra única), Assinatura mensal recorrente, e se há Implementação inicial. Pelo menos uma precisa estar marcada.",
  "modalidades de contratacao por periodo": "Descontos e condições por período de contrato (mensal, trimestral, semestral, anual etc.).",
  "implementacao inicial": "Etapa única de configuração/onboarding cobrada à parte no início do contrato.",
  "entrega emergencial": "Opção em que o cliente paga um adicional para receber mais rápido. Cada etapa define quantas horas reduz e quanto cobra a mais.",
  "oferecer entrega emergencial": "Liga a opção de entrega emergencial neste produto. Sem nenhuma etapa configurada ela não aparece para o cliente e a publicação é bloqueada.",
  // ── Tarefa e etapas
  "nome da nova tarefa": "Nome da tarefa principal do produto (o trabalho que a equipe executa). Em produto individual existe uma única tarefa.",
  "nome da etapa": "Nome curto do passo dentro da tarefa (ex.: Briefing, Produção, Revisão). Cada etapa tem horas, executor e checklist próprios.",
  "nome": "Nome do item como será mostrado.",
  "o que e": "O que acontece nesta etapa: nome e descrição objetiva do que o executor deve fazer.",
  "descricao (o que acontece nesta etapa)": "Explique o que o executor faz nesta etapa, para quem vai executar entender sem perguntar.",
  "finalidade": "Para que serve a etapa: o resultado que ela precisa gerar para a próxima etapa ou para o cliente.",
  "quem faz e quanto tempo": "Quem executa a etapa (humano, IA ou híbrido), a especialidade exigida e as horas previstas. As horas definem o custo e o prazo da etapa.",
  "quem executa": "Tipo de executor da etapa: humano (nômade/líder), IA, ou humano ou IA (quem contrata escolhe). Filtra as especialidades disponíveis.",
  "especialidade": "Especialidade profissional exigida (define o valor/hora e o filtro de quem pode executar).",
  "horas estimadas": "Horas de trabalho previstas para esta etapa. A tarefa soma as horas das etapas e o custo é calculado a partir delas.",
  "tempo estimado": "Tempo previsto de trabalho. Em horas; a tarefa soma o tempo das etapas.",
  "tempo previsto": "Tempo previsto de trabalho desta etapa, usado no custo e no prazo.",
  "quem recebe a etapa": "Quem recebe a etapa quando ela abre: nômade (rodízio/vaga), líder da área (o de menos tarefas abertas), um líder específico, ou equipe interna.",
  "qual lider": "O líder que sempre receberá esta etapa. Precisa estar ativo na plataforma.",
  "quando termina": "Como se considera a etapa concluída: critério de conclusão e evidência exigida.",
  "criterio de conclusao": "Condição objetiva para dar a etapa como pronta (ex.: arquivo final entregue e aprovado no checklist).",
  "checklist, orientacoes e evidencia": "Itens de conferência (execução, qualificação e aprovação), orientações para quem executa e se a etapa exige anexo como prova.",
  "orientacoes para execucao": "Instruções passo a passo para quem vai executar a etapa. Aparecem para o executor na tela dele.",
  "evidencia obrigatoria": "Quando ligado, a etapa só pode ser concluída depois de anexar uma evidência (link ou arquivo).",
  "responsavel pela evidencia": "Quem envia ou confere a evidência da etapa: o executor, o líder ou o cliente.",
  "exemplo de evidencia": "Exemplo do que vale como evidência (ex.: print do anúncio publicado). Ajuda o executor a entregar certo.",
  "quando comeca": "Quando a etapa abre: depois da anterior, junto com o início da tarefa, ou depois de etapas específicas. Permite etapas em paralelo.",
  "fluxo das etapas": "Mostra e edita a ordem entre as etapas: quais rodam juntas, quais esperam outras e qual regra de executor cada uma segue.",
  "etapa interna (o cliente nao ve nem aprova)": "Etapa só da equipe: o cliente não a vê nem aprova (ex.: validação de acessos). O líder pode avisar o cliente se achar um problema.",
  "etapa interna": "Etapa só da equipe: o cliente não a vê nem aprova.",
  "passa pela qualificacao do lider": "Depois de entregue, o líder confere (qualifica) antes de a etapa seguir para aprovação ou para a próxima.",
  "qualificacao do lider": "O líder confere a etapa depois da entrega, antes do cliente.",
  "libera a proxima etapa automaticamente": "Depois de aprovada, a próxima etapa abre sozinha. Desligado: o líder precisa liberar manualmente.",
  "libera a proxima sozinha": "Depois de aprovada, a próxima etapa abre sozinha. Desligado: o líder precisa liberar manualmente.",
  "execucao por etapa": "Cada etapa passa por entrega, qualificação e aprovação antes de liberar a próxima, em vez de só no fim da tarefa.",
  "pagamento do nomade": "Quando o nômade recebe: a cada etapa aprovada, ou só no fim da tarefa (créditos retidos até a última etapa).",
  "prazo de aprovacao do cliente": "Quantas horas úteis o cliente tem para aprovar esta etapa. Vazio = prazo padrão.",
  "prazo de refacao": "Quantas horas úteis o executor tem para refazer a etapa depois de uma reprovação. Vazio = mantém o prazo anterior.",
  "prazo de aceite do preferido": "Horas que o executor preferido tem para aceitar esta etapa antes de ela abrir para os demais. Vazio = padrão da plataforma (2 h).",
  "executor": "Quem executa: nômade, líder, equipe interna ou IA.",
  "executor aciona": "A IA/execução automática só começa depois que o executor aciona.",
  "lider aciona": "A execução só começa depois que o líder aciona.",
  "um humano assume se a ia nao conseguir": "Se a IA falhar ou ficar abaixo da qualidade, um profissional humano assume a etapa.",
  "continuidade do executor": "Se, em ciclos seguintes, o mesmo executor deve continuar (não permitido, preferido ou obrigatório).",
  "dispensavel quando o mesmo executor continua": "A etapa pode ser pulada quando o mesmo executor já trabalhou nela no ciclo anterior.",
  "ciclo": "Como a tarefa se comporta em contratos recorrentes: só no primeiro ciclo, em todos ou em ciclos específicos.",
  "repeticao": "Regra de repetição da tarefa nos ciclos de uma assinatura (todos os ciclos, a cada X ciclos, só na primeira vez).",
  "so na primeira execucao": "A tarefa roda apenas na primeira execução do contrato (ex.: configuração inicial).",
  "regra de acessos": "Como os acessos do cliente são aproveitados entre ciclos: pedir só na primeira vez, revalidar de tempos em tempos ou sempre.",
  "condicional": "Tarefa/etapa que só entra se uma condição, variação ou adicional escolhido pelo cliente exigir.",
  "exige aprovacao": "O cliente precisa aprovar antes de seguir.",
  "aprovacao do cliente": "O cliente aprova a entrega antes de ela ser considerada concluída.",
  "exige revisao humana": "Um humano revisa o que a IA entregou antes de seguir.",
  "revisao humana obrigatoria": "Um humano precisa revisar o resultado da IA antes de ele chegar ao cliente.",
  "qualificacao obrigatoria": "A tarefa só segue depois da qualificação (conferência) do líder.",
  "aplicar a todas as tarefas": "Aplica esta configuração a todas as tarefas do produto de uma vez.",
  "tarefa": "A tarefa do produto a que este item se refere.",
  "etapa": "A etapa da tarefa a que este item se refere.",
  "esta tarefa abre depois de outra ser finalizada": "Dependência entre tarefas: esta tarefa só começa depois que a escolhida for finalizada.",
  "resumo de dependencias": "Resumo das regras de dependência: quais tarefas esperam outras e como as etapas se encadeiam (paralelo, depois de, mesmo executor).",
  "dependencias": "Ordem em que as tarefas e etapas começam. Entre etapas: use \"Quando começa\" e o \"Fluxo das etapas\". Entre tarefas (combos): dentro da tarefa.",
  // ── Acessos / conexões
  "tipo de acesso": "Qual acesso o cliente precisa liberar (Google Ads, Meta, Analytics, CRM, site…).",
  "como sera liberado": "A forma de liberar o acesso: convite por e-mail, compartilhamento de conta, token etc. As opções dependem do tipo de acesso.",
  "permissao necessaria": "Nível de permissão que o acesso precisa ter (leitura, edição, administrador…). Peça só o necessário.",
  "obrigatoriedade": "Se o acesso é obrigatório, opcional ou condicional (só quando uma condição acontece).",
  "quando sera necessaria": "Em que momento o acesso passa a ser necessário (antes de começar, antes de uma tarefa/etapa ou em uma condição).",
  "condicao (quando passa a ser necessaria)": "Descreva quando este acesso passa a ser exigido.",
  "comportamento quando pendente": "O que acontece se o acesso não for liberado: bloqueia o início, apenas avisa ou deixa seguir.",
  "escopo de uso sugerido": "Para quem o acesso vale: só este projeto, todos os projetos do cliente etc.",
  "modo de validacao": "Como o acesso é conferido (manual pela equipe, automático ou leve).",
  "regra de revalidacao": "Quando o acesso precisa ser conferido de novo (nunca, a cada X dias, em cada ciclo).",
  "revalidar a cada (dias)": "Intervalo, em dias, para conferir novamente se o acesso continua funcionando.",
  "lembrete a cada (horas)": "De quantas em quantas horas o cliente é lembrado de liberar o acesso.",
  "limite de lembretes": "Máximo de lembretes enviados ao cliente antes de parar.",
  "escalonar apos (lembretes)": "Depois de quantos lembretes sem resposta o caso é escalado para a equipe interna.",
  "motivo (mostrado ao cliente)": "Por que este acesso é necessário. O cliente lê esse texto ao ser solicitado.",
  "instrucoes especificas deste produto": "Passo a passo extra, específico deste produto, para o cliente liberar o acesso.",
  "conferencia leve ao reaproveitar": "Ao reaproveitar um acesso já liberado em outro produto, faz só uma conferência rápida.",
  "visivel para o cliente": "O cliente enxerga este item na tela dele.",
  "outro acesso necessario": "Descreva um acesso que não está na lista padrão.",
  "6. tarefas ou etapas dependentes": "Tarefas ou etapas que só podem começar depois que este acesso for liberado.",
  "esta etapa precisa de acesso": "Marque se esta etapa depende de um acesso do cliente.",
  "esta precisa de acesso": "Marque se esta etapa depende de um acesso do cliente.",
  // ── Variações, adicionais, condições
  "adicionais": "Itens extras que o cliente pode somar ao produto, com custo, prazo e esforço próprios.",
  "tipo de escolha": "Como o cliente escolhe: uma opção (única), várias, ou por quantidade.",
  "tipo": "Categoria do item. A lista de opções muda conforme o campo.",
  "quantidade": "Quantidade do item. Define quanto é cobrado/entregue.",
  "valor padrao": "Valor usado quando o cliente não escolhe nada.",
  "unidade": "Unidade em que a quantidade é contada (campanhas, páginas, posts…).",
  "minimo": "Menor valor aceito.",
  "maximo": "Maior valor aceito.",
  "obrigatorio": "O cliente precisa responder/escolher para continuar.",
  "obrigatoria": "O cliente precisa responder/escolher para continuar.",
  "nova condicao": "Regra que altera prazo, preço, tarefas ou entregáveis quando o cliente faz certa escolha.",
  "quantidade de campanhas": "Quantas campanhas entram na contratação (cada campanha pode somar custo e prazo).",
  "× quantidade": "Multiplica o efeito pela quantidade escolhida pelo cliente.",
  "aprovacao cliente": "O cliente precisa aprovar esta tarefa/etapa antes de ela ser concluída.",
  "exige comentario": "Quem aprova ou reprova precisa escrever um comentário.",
  "revisao obrigatoria": "Um humano revisa a entrega antes de seguir.",
  "detalhes avancados (operacao)": "Configurações operacionais menos usadas: lembretes, revalidação, escopo e instruções específicas.",
  "x quantidade": "Quantidade multiplicadora do efeito.",
  "do ciclo": "Ciclo da assinatura em que a regra começa a valer.",
  "ate o": "Ciclo da assinatura até o qual a regra vale.",
  "ate": "Limite final do período.",
  "de": "Início do período.",
  // ── Questionário
  "questionario": "Perguntas que o cliente responde ao contratar; as respostas orientam a equipe e a IA.",
  "nome do questionario": "Nome interno do conjunto de perguntas.",
  "nova pergunta": "Texto da pergunta que o cliente vai responder.",
  "opcoes (uma por linha, minimo 2)": "As alternativas de escolha, uma por linha. Mínimo de duas.",
  "resposta usada por": "Onde a resposta é usada: na equipe, na IA, no preço ou em condições do produto.",
  "quem ve": "Quem enxerga esta pergunta/resposta: cliente, agência, executor, líder ou só equipe interna.",
  "texto de ajuda (o cliente ve)": "Dica mostrada ao cliente abaixo da pergunta.",
  "ajuda para o cliente": "Explicação curta mostrada ao cliente para ele responder corretamente.",
  "mensagem ao cliente (opcional)": "Mensagem extra mostrada ao cliente quando este item é ativado.",
  "disponibilidade": "Se o item está disponível, em pré-lançamento, pausado ou esgotado.",
  "min. caracteres": "Quantidade mínima de caracteres que a resposta/texto deve ter.",
  "max. caracteres": "Quantidade máxima de caracteres que a resposta/texto pode ter.",
  "min. palavras": "Quantidade mínima de palavras do texto gerado pela IA.",
  "max. palavras": "Quantidade máxima de palavras do texto gerado pela IA.",
  "max. arquivos": "Quantos arquivos o cliente pode anexar na resposta.",
  "tamanho max. (mb)": "Tamanho máximo, em megabytes, de cada arquivo anexado.",
  // ── IA
  "tamanho": "Tamanho do texto que a IA deve gerar: manter, curto, médio ou longo.",
  "pesquisar na internet (como o produto e conhecido hoje)": "A IA pesquisa na internet como o produto/serviço é descrito hoje no mercado e usa isso no texto. Com pouco texto no campo, a pesquisa é usada automaticamente.",
  "perfil ativo": "Perfil de IA que está valendo para este produto/tarefa.",
  "resumo por ia": "Resumo gerado pela IA a partir do conteúdo do produto.",
  "entendo que o teste chama a ia e pode gerar custo": "Confirma que o teste faz uma chamada real à IA, que pode gerar custo.",
  "versoes do prompt": "Histórico das versões das instruções (prompt) da IA.",
  // ── Preço e prazo
  "composicao do preco": "Como o preço final é formado: custo das horas, taxas, impostos, comissão e margem.",
  "memoria de calculo": "Passo a passo do cálculo de preço e prazo, para auditoria.",
  "custos e encargos": "Custos das tarefas e taxas aplicadas sobre eles.",
  "diagnostico de precificacao": "Aponta o que falta ou está inconsistente para o preço ser calculado.",
  "simular cenario": "Simula preço e prazo para uma combinação de escolhas do cliente, sem criar cotação.",
  "referencia historica de preco": "Preço antigo, só para comparação. Nunca é usado para cobrar.",
  "regras comerciais": "Regras de venda do produto (modalidades, descontos, prazos).",
  "regras de prazo": "Regras que somam ou reduzem o prazo conforme as escolhas do cliente.",
  "prazos estruturados": "Prazos definidos por regra (SLA): início, tarefa, etapa, aprovação, entrega.",
  "portoes de aprovacao": "Pontos em que alguém precisa aprovar antes de continuar (antes de iniciar uma etapa, depois dela ou antes de publicar).",
  "motivos de pausa do relogio": "Motivos que pausam o prazo (SLA), como aguardando o cliente ou acesso pendente.",
  "custo (r$)": "Custo em reais do item.",
  "percentual demonstrativo (%)": "Percentual usado só para demonstrar o cálculo.",
  "valor/hora (opcional)": "Valor da hora desta especialidade. Opcional.",
  // ── Publicação / versões
  "nome da versao": "Nome da nova versão do produto.",
  "criar nova versao": "Cria uma nova versão editável a partir da publicada, sem alterar o que o cliente vê até publicar.",
  "copiar dados do rascunho": "A nova versão já nasce com os dados do rascunho atual.",
  "versao atual": "A versão que está em edição ou publicada agora.",
  "versoes anteriores": "Versões antigas do produto, para consulta.",
  "historico da versao": "Registro de tudo que mudou nesta versão.",
  "atividade da versao": "Eventos recentes desta versão (edições, validações, publicações).",
  "resumo da versao": "Principais configurações da versão atual.",
  "resumo das alteracoes": "Descreva o que mudou nesta versão (aparece no histórico).",
  "tipo de alteracao": "Natureza da mudança: texto, preço, prazo, escopo etc.",
  "pronto para publicar?": "Lista do que ainda impede a publicação. Tudo precisa estar resolvido.",
  "ver detalhes dos bloqueios": "Mostra cada pendência que impede a publicação.",
  "pendencias para decisao": "Itens que precisam de uma decisão sua antes de seguir.",
  "divergencias registradas (nunca ocultadas)": "Diferenças encontradas ao importar dados; ficam registradas para você decidir.",
  "textos originais preservados": "Textos originais da importação, mantidos sem alteração.",
  "revisao / status": "Situação da revisão do item.",
  "ver alteracoes detalhadas": "Mostra o antes e o depois de cada campo alterado.",
  "historico de resolucoes": "Registro das decisões tomadas sobre divergências.",
  "revisao da rose": "Revisão do conteúdo feita pela equipe antes de publicar.",
  "planilha principal (fonte da identidade)": "Planilha que define a identidade dos produtos importados.",
  "endereco (slug) — so mude se tiver certeza": "Endereço do produto na URL. Mudar quebra links antigos.",
  "este produto gera uma nova entrega todo mes": "Marque se o produto entrega algo novo a cada mês na assinatura.",
  "resultado": "Resultado do cálculo ou da validação.",
  "key": "Identificador interno (sem espaços). Não aparece para o cliente.",
  "rotulo": "Texto que o cliente vê para esta opção.",
  "sob orcamento": "Produto sem preço fechado: o cliente pede um orçamento.",
  "condicional (so entra se uma condicao exigir)": "Só entra quando uma condição exigir.",
};

/** Procura a ajuda de um campo em um dicionário (chave normalizada). Ignora "(...)" no fim e o que vem depois de " — ". */
export function lookupHelp(dict: Record<string, string>, rawText: string): string | null {
  const t = normalizeHelpKey(rawText);
  if (!t || t.length > 120) return null;
  if (dict[t]) return dict[t];
  const stripParen = (v: string) => v.replace(/\s*\([^)]*\)\s*$/, "").trim();
  const noParen = stripParen(t);
  if (noParen !== t && dict[noParen]) return dict[noParen];
  const noDash = t.split(" — ")[0]?.trim();
  if (noDash && noDash !== t) {
    if (dict[noDash]) return dict[noDash];
    const nd = stripParen(noDash);
    if (dict[nd]) return dict[nd];
  }
  return null;
}
export function helpFor(rawText: string): string | null {
  return lookupHelp(H, rawText);
}

export const HELP_KEYS = Object.keys(H);
