// Shared mock project data used by both admin/projetos and the company Projetos tab.
// companyId maps to the company IDs in admin/empresas mockCompanies.
//   1 = Coca-Cola Brasil
//   2 = Starbucks Coffee
//   3 = Fundação Wikimedia

export const mockProjects = [
  {
    id: 1,
    name: "Hospedagem Florescer Idosos",
    client: "Florescer",
    clientCNPJ: "12.345.678/0001-90",
    agency: "Lamego Academy",
    companyType: "agency",
    consultant: "Equipe Lamego",
    consultantEmail: "contato@lamego.com.vc",
    type: "Marketing Digital",
    status: "awaiting-payment",
    progress: 65,
    budget: 15000,
    spent: 9750,
    createdDate: "19/02/2025",
    startDate: "2024-01-15",
    deadline: "2024-03-30",
    team: 5,
    nomades: ["Ana Santos", "Carlos Lima"],
    bitrixSync: false,
    portfolioPermission: false,
    overdue: false,
    value: 15000,
    fromLead: true,
    tasks: 12,
    companyId: 1,
  },
  {
    id: 2,
    name: "Redesign Website Startup ABC",
    client: "Startup ABC",
    clientCNPJ: "98.765.432/0001-10",
    agency: "Design Studio",
    companyType: "agency",
    consultant: "Maria Designer",
    consultantEmail: "maria@designstudio.com",
    type: "Desenvolvimento Web",
    status: "in-progress",
    progress: 45,
    budget: 25000,
    spent: 11250,
    createdDate: "15/01/2025",
    startDate: "2024-02-01",
    deadline: "2024-05-15",
    team: 3,
    nomades: ["Maria Silva", "João Dev"],
    bitrixSync: true,
    portfolioPermission: true,
    overdue: false,
    value: 25000,
    fromLead: false,
    tasks: 18,
    companyId: 1,
  },
  {
    id: 3,
    name: "Identidade Visual FoodCorp",
    client: "FoodCorp",
    clientCNPJ: "11.222.333/0001-44",
    agency: "Creative Partners",
    companyType: "agency",
    consultant: "Pedro Criativo",
    consultantEmail: "pedro@creative.com",
    type: "Design",
    status: "completed",
    progress: 100,
    budget: 8000,
    spent: 7800,
    createdDate: "10/12/2024",
    startDate: "2023-12-10",
    deadline: "2024-01-20",
    team: 2,
    nomades: ["Ana Santos"],
    bitrixSync: true,
    portfolioPermission: false,
    overdue: false,
    value: 8000,
    fromLead: true,
    tasks: 7,
    companyId: 1,
  },
  {
    id: 4,
    name: "Campanha Lançamento Produto XYZ",
    client: "Tech Innovations",
    clientCNPJ: "22.333.444/0001-55",
    agency: "Marketing Pro",
    companyType: "agency",
    consultant: "Lucas Marketing",
    consultantEmail: "lucas@marketingpro.com",
    type: "Marketing Digital",
    status: "negotiation",
    progress: 20,
    budget: 32000,
    spent: 6400,
    createdDate: "05/02/2025",
    startDate: "2024-03-01",
    deadline: "2024-06-30",
    team: 4,
    nomades: ["Carlos Lima", "Ana Santos"],
    bitrixSync: true,
    portfolioPermission: true,
    overdue: false,
    value: 32000,
    fromLead: true,
    tasks: 25,
    companyId: 1,
  },
  {
    id: 5,
    name: "E-commerce Loja Virtual Fashion Style Boutique",
    client: "Fashion Style",
    clientCNPJ: "33.444.555/0001-66",
    agency: "WebDev Solutions",
    companyType: "agency",
    consultant: "Fernanda Tech",
    consultantEmail: "fernanda@webdev.com",
    type: "E-commerce",
    status: "draft",
    progress: 5,
    budget: 45000,
    spent: 2250,
    createdDate: "01/02/2025",
    startDate: "2024-04-01",
    deadline: "2024-08-15",
    team: 6,
    nomades: ["João Dev", "Maria Silva", "Pedro Criativo"],
    bitrixSync: false,
    portfolioPermission: false,
    overdue: false,
    value: 45000,
    fromLead: false,
    tasks: 20,
    companyId: 1,
  },
  {
    id: 6,
    name: "App Mobile Delivery Express",
    client: "Delivery Express",
    clientCNPJ: "44.555.666/0001-77",
    agency: "Mobile Masters",
    companyType: "nomad",
    consultant: "Ricardo Apps",
    consultantEmail: "ricardo@mobilemasters.com",
    type: "Desenvolvimento Mobile",
    status: "in-progress",
    progress: 70,
    budget: 62000,
    spent: 43400,
    createdDate: "20/12/2024",
    startDate: "2023-11-15",
    deadline: "2024-04-30",
    team: 7,
    nomades: ["Ana Santos", "João Dev", "Carlos Lima"],
    bitrixSync: true,
    portfolioPermission: true,
    overdue: false,
    value: 62000,
    fromLead: true,
    tasks: 38,
    companyId: 1,
  },
  {
    id: 7,
    name: "Sistema CRM Empresarial",
    client: "Corporação Global",
    clientCNPJ: "55.666.777/0001-88",
    agency: "Enterprise Software",
    companyType: "company",
    consultant: "Beatriz Systems",
    consultantEmail: "beatriz@enterprise.com",
    type: "Desenvolvimento Web",
    status: "awaiting-payment",
    progress: 90,
    budget: 78000,
    spent: 70200,
    createdDate: "15/11/2024",
    startDate: "2023-10-01",
    deadline: "2024-02-28",
    team: 8,
    nomades: ["Maria Silva", "Pedro Criativo", "João Dev"],
    bitrixSync: true,
    portfolioPermission: false,
    overdue: true,
    value: 78000,
    fromLead: false,
    tasks: 45,
    companyId: 2,
  },
  {
    id: 8,
    name: "Consultoria SEO Avançada",
    client: "Digital Ventures",
    clientCNPJ: "66.777.888/0001-99",
    agency: "SEO Masters",
    companyType: "agency",
    consultant: "Gabriel SEO",
    consultantEmail: "gabriel@seomasters.com",
    type: "Consultoria",
    status: "in-progress",
    progress: 15,
    budget: 18000,
    spent: 2700,
    createdDate: "10/02/2025",
    startDate: "2024-03-15",
    deadline: "2024-05-30",
    team: 2,
    nomades: ["Ana Santos"],
    bitrixSync: false,
    portfolioPermission: true,
    overdue: false,
    value: 18000,
    fromLead: true,
    tasks: 10,
    companyId: 2,
  },
  {
    id: 9,
    name: "Plataforma de Cursos Online",
    client: "EduTech Brasil",
    clientCNPJ: "77.888.999/0001-01",
    agency: "Learning Solutions",
    companyType: "agency",
    consultant: "Amanda Educação",
    consultantEmail: "amanda@learning.com",
    type: "Desenvolvimento Web",
    status: "in-progress",
    progress: 55,
    budget: 48000,
    spent: 26400,
    createdDate: "25/01/2025",
    startDate: "2024-02-10",
    deadline: "2024-06-20",
    team: 5,
    nomades: ["João Dev", "Maria Silva"],
    bitrixSync: true,
    portfolioPermission: true,
    overdue: false,
    value: 48000,
    fromLead: true,
    tasks: 30,
    companyId: 2,
  },
  {
    id: 10,
    name: "App Fitness Tracker Premium",
    client: "Health & Wellness Co",
    clientCNPJ: "88.999.000/0001-12",
    agency: "Fitness Apps",
    companyType: "nomad",
    consultant: "Roberto Health",
    consultantEmail: "roberto@fitnessapps.com",
    type: "Desenvolvimento Mobile",
    status: "in-progress",
    progress: 38,
    budget: 35000,
    spent: 13300,
    createdDate: "18/01/2025",
    startDate: "2024-01-25",
    deadline: "2024-05-05",
    team: 4,
    nomades: ["Carlos Lima", "Ana Santos"],
    bitrixSync: true,
    portfolioPermission: false,
    overdue: false,
    value: 35000,
    fromLead: false,
    tasks: 22,
    companyId: 3,
  },
  {
    id: 11,
    name: "Sistema de Gestão Hospitalar",
    client: "Hospital São Lucas",
    clientCNPJ: "99.000.111/0001-23",
    agency: "Healthcare Systems",
    companyType: "company",
    consultant: "Dra. Patricia Tech",
    consultantEmail: "patricia@healthcare.com",
    type: "Desenvolvimento Web",
    status: "in-progress",
    progress: 72,
    budget: 95000,
    spent: 68400,
    createdDate: "05/12/2024",
    startDate: "2023-11-01",
    deadline: "2024-04-15",
    team: 9,
    nomades: ["João Dev", "Maria Silva", "Pedro Criativo"],
    bitrixSync: true,
    portfolioPermission: true,
    overdue: false,
    value: 95000,
    fromLead: true,
    tasks: 56,
    companyId: 3,
  },
  {
    id: 12,
    name: "Portal de Notícias Regional",
    client: "Jornal Cidade Nova",
    clientCNPJ: "00.111.222/0001-34",
    agency: "Media Digital",
    companyType: "company",
    consultant: "Juliana Jornalismo",
    consultantEmail: "juliana@mediadigital.com",
    type: "Desenvolvimento Web",
    status: "in-progress",
    progress: 50,
    budget: 28000,
    spent: 14000,
    createdDate: "12/01/2025",
    startDate: "2024-02-05",
    deadline: "2024-05-25",
    team: 3,
    nomades: ["Ana Santos"],
    bitrixSync: false,
    portfolioPermission: true,
    overdue: false,
    value: 28000,
    fromLead: true,
    tasks: 16,
    companyId: 3,
  },
]
