// Shared mock project data used by both admin/projetos and the company Projetos tab.
// companyId maps to the company IDs in admin/empresas mockCompanies.
//   1  = Coca-Cola Brasil       (company)
//   2  = Starbucks Coffee        (agency)
//   3  = Fundação Wikimedia      (company)
//   4  = Agência Criativa Hub    (agency)
//   5  = Nomade Freelancer Co    (nomad)
//   7  = Studio Mídias Sociais   (agency)
//  10  = Meta Business           (company)
//  12  = Nômade Criativo 360     (nomad)
//  13  = Google Brasil           (company)
//  14  = MarcaForte Agência      (agency)
//  15  = Slack do Brasil         (company)
//  17  = Conecta Agências        (agency)

export const mockProjects = [
  {
    id: 1,
    name: "Hospedagem Florescer Idosos",
    client: "Florescer",
    clientCNPJ: "12.345.678/0001-90",
    agency: "Coca-Cola Brasil",
    companyType: "company",
    consultant: "Carlos Mendes",
    consultantEmail: "carlos@cocacola.com.br",
    type: "Marketing Digital",
    status: "awaiting-payment",
    progress: 65,
    budget: 15000,
    spent: 9750,
    createdDate: "19/02/2025",
    startDate: "2024-01-15",
    deadline: "2024-03-30",
    team: 5,
    nomades: ["Ana Santos", "Carlos Lima"],
    bitrixSync: false,
    portfolioPermission: false,
    overdue: false,
    value: 15000,
    fromLead: true,
    tasks: 12,
    companyId: 1,
  },
  {
    id: 2,
    name: "Redesign Website Startup ABC",
    client: "Startup ABC",
    clientCNPJ: "98.765.432/0001-10",
    agency: "Starbucks Coffee",
    companyType: "agency",
    consultant: "Renata Ferreira",
    consultantEmail: "renata@starbucks.com.br",
    type: "Desenvolvimento Web",
    status: "in-progress",
    progress: 45,
    budget: 25000,
    spent: 11250,
    createdDate: "15/01/2025",
    startDate: "2024-02-01",
    deadline: "2024-05-15",
    team: 3,
    nomades: ["Maria Silva", "João Dev"],
    bitrixSync: true,
    portfolioPermission: true,
    overdue: false,
    value: 25000,
    fromLead: false,
    tasks: 18,
    companyId: 2,
  },
  {
    id: 3,
    name: "Identidade Visual FoodCorp",
    client: "FoodCorp",
    clientCNPJ: "11.222.333/0001-44",
    agency: "Agência Criativa Hub",
    companyType: "agency",
    consultant: "Pedro Criativo",
    consultantEmail: "pedro@criativahub.com.br",
    type: "Design",
    status: "completed",
    progress: 100,
    budget: 8000,
    spent: 7800,
    createdDate: "10/12/2024",
    startDate: "2023-12-10",
    deadline: "2024-01-20",
    team: 2,
    nomades: ["Ana Santos"],
    bitrixSync: true,
    portfolioPermission: false,
    overdue: false,
    value: 8000,
    fromLead: true,
    tasks: 7,
    companyId: 4,
  },
  {
    id: 4,
    name: "Campanha Lançamento Produto XYZ",
    client: "Tech Innovations",
    clientCNPJ: "22.333.444/0001-55",
    agency: "Fundação Wikimedia",
    companyType: "company",
    consultant: "Lucas Oliveira",
    consultantEmail: "lucas@wikimedia.org.br",
    type: "Marketing Digital",
    status: "negotiation",
    progress: 20,
    budget: 32000,
    spent: 6400,
    createdDate: "05/02/2025",
    startDate: "2024-03-01",
    deadline: "2024-06-30",
    team: 4,
    nomades: ["Carlos Lima", "Ana Santos"],
    bitrixSync: true,
    portfolioPermission: true,
    overdue: false,
    value: 32000,
    fromLead: true,
    tasks: 25,
    companyId: 3,
  },
  {
    id: 5,
    name: "E-commerce Loja Virtual Fashion Style Boutique",
    client: "Fashion Style",
    clientCNPJ: "33.444.555/0001-66",
    agency: "Nomade Freelancer Co",
    companyType: "nomad",
    consultant: "Fernanda Ribeiro",
    consultantEmail: "oi@nomadefreelancer.io",
    type: "E-commerce",
    status: "draft",
    progress: 5,
    budget: 45000,
    spent: 2250,
    createdDate: "01/02/2025",
    startDate: "2024-04-01",
    deadline: "2024-08-15",
    team: 6,
    nomades: ["João Dev", "Maria Silva", "Pedro Criativo"],
    bitrixSync: false,
    portfolioPermission: false,
    overdue: false,
    value: 45000,
    fromLead: false,
    tasks: 20,
    companyId: 5,
  },
  {
    id: 6,
    name: "App Mobile Delivery Express",
    client: "Delivery Express",
    clientCNPJ: "44.555.666/0001-77",
    agency: "Conecta Agências",
    companyType: "agency",
    consultant: "Ricardo Souza",
    consultantEmail: "parcerias@conectaagencias.com",
    type: "Desenvolvimento Mobile",
    status: "in-progress",
    progress: 70,
    budget: 62000,
    spent: 43400,
    createdDate: "20/12/2024",
    startDate: "2023-11-15",
    deadline: "2024-04-30",
    team: 7,
    nomades: ["Ana Santos", "João Dev", "Carlos Lima"],
    bitrixSync: true,
    portfolioPermission: true,
    overdue: false,
    value: 62000,
    fromLead: true,
    tasks: 38,
    companyId: 17,
  },
  {
    id: 7,
    name: "Sistema CRM Empresarial",
    client: "Corporação Global",
    clientCNPJ: "55.666.777/0001-88",
    agency: "Meta Business",
    companyType: "company",
    consultant: "Beatriz Rodrigues",
    consultantEmail: "rh@metabusiness.com.br",
    type: "Desenvolvimento Web",
    status: "awaiting-payment",
    progress: 90,
    budget: 78000,
    spent: 70200,
    createdDate: "15/11/2024",
    startDate: "2023-10-01",
    deadline: "2024-02-28",
    team: 8,
    nomades: ["Maria Silva", "Pedro Criativo", "João Dev"],
    bitrixSync: true,
    portfolioPermission: false,
    overdue: true,
    value: 78000,
    fromLead: false,
    tasks: 45,
    companyId: 10,
  },
  {
    id: 8,
    name: "Consultoria SEO Avançada",
    client: "Digital Ventures",
    clientCNPJ: "66.777.888/0001-99",
    agency: "MarcaForte Agência",
    companyType: "agency",
    consultant: "Gabriel Costa",
    consultantEmail: "ola@marcaforteagencia.com.br",
    type: "Consultoria",
    status: "in-progress",
    progress: 15,
    budget: 18000,
    spent: 2700,
    createdDate: "10/02/2025",
    startDate: "2024-03-15",
    deadline: "2024-05-30",
    team: 2,
    nomades: ["Ana Santos"],
    bitrixSync: false,
    portfolioPermission: true,
    overdue: false,
    value: 18000,
    fromLead: true,
    tasks: 10,
    companyId: 14,
  },
  {
    id: 9,
    name: "Plataforma de Cursos Online",
    client: "EduTech Brasil",
    clientCNPJ: "77.888.999/0001-01",
    agency: "Studio Mídias Sociais",
    companyType: "agency",
    consultant: "Amanda Barros",
    consultantEmail: "studio@midiassociais.net",
    type: "Desenvolvimento Web",
    status: "in-progress",
    progress: 55,
    budget: 48000,
    spent: 26400,
    createdDate: "25/01/2025",
    startDate: "2024-02-10",
    deadline: "2024-06-20",
    team: 5,
    nomades: ["João Dev", "Maria Silva"],
    bitrixSync: true,
    portfolioPermission: true,
    overdue: false,
    value: 48000,
    fromLead: true,
    tasks: 30,
    companyId: 7,
  },
  {
    id: 10,
    name: "App Fitness Tracker Premium",
    client: "Health & Wellness Co",
    clientCNPJ: "88.999.000/0001-12",
    agency: "Nômade Criativo 360",
    companyType: "nomad",
    consultant: "Roberto Nunes",
    consultantEmail: "eu@nomadecriativo.me",
    type: "Desenvolvimento Mobile",
    status: "in-progress",
    progress: 38,
    budget: 35000,
    spent: 13300,
    createdDate: "18/01/2025",
    startDate: "2024-01-25",
    deadline: "2024-05-05",
    team: 4,
    nomades: ["Carlos Lima", "Ana Santos"],
    bitrixSync: true,
    portfolioPermission: false,
    overdue: false,
    value: 35000,
    fromLead: false,
    tasks: 22,
    companyId: 12,
  },
  {
    id: 11,
    name: "Sistema de Gestão Hospitalar",
    client: "Hospital São Lucas",
    clientCNPJ: "99.000.111/0001-23",
    agency: "Google Brasil",
    companyType: "company",
    consultant: "Patricia Lima",
    consultantEmail: "negocios@google.com.br",
    type: "Desenvolvimento Web",
    status: "in-progress",
    progress: 72,
    budget: 95000,
    spent: 68400,
    createdDate: "05/12/2024",
    startDate: "2023-11-01",
    deadline: "2024-04-15",
    team: 9,
    nomades: ["João Dev", "Maria Silva", "Pedro Criativo"],
    bitrixSync: true,
    portfolioPermission: true,
    overdue: false,
    value: 95000,
    fromLead: true,
    tasks: 56,
    companyId: 13,
  },
  {
    id: 12,
    name: "Portal de Notícias Regional",
    client: "Jornal Cidade Nova",
    clientCNPJ: "00.111.222/0001-34",
    agency: "Slack do Brasil",
    companyType: "company",
    consultant: "Juliana Teixeira",
    consultantEmail: "ti@slack.com.br",
    type: "Desenvolvimento Web",
    status: "in-progress",
    progress: 50,
    budget: 28000,
    spent: 14000,
    createdDate: "12/01/2025",
    startDate: "2024-02-05",
    deadline: "2024-05-25",
    team: 3,
    nomades: ["Ana Santos"],
    bitrixSync: false,
    portfolioPermission: true,
    overdue: false,
    value: 28000,
    fromLead: true,
    tasks: 16,
    companyId: 15,
  },
]
