param()
$f = Join-Path $PSScriptRoot "app\admin\modelos-tarefas\page.tsx"
$c = [System.IO.File]::ReadAllText($f, [System.Text.Encoding]::UTF8)
$fd = [char]0xFFFD

function Fix($s, $from, $to) { return $s.Replace($from, $to) }

$c = Fix $c "Em Revis${fd}o" "Em Revis$([char]0xE3)o"
$c = Fix $c "Execu${fd}${fd}o" "Execu$([char]0xE7)$([char]0xE3)o"
$c = Fix $c "Aprova${fd}${fd}o" "Aprova$([char]0xE7)$([char]0xE3)o"
$c = Fix $c "Qualifica${fd}${fd}o" "Qualifica$([char]0xE7)$([char]0xE3)o"
$c = Fix $c "Intermedi${fd}ria" "Intermedi$([char]0xE1)ria"
$c = Fix $c "Avan${fd}ada" "Avan$([char]0xE7)ada"
$c = Fix $c "B${fd}sica" "B$([char]0xE1)sica"
$c = Fix $c "M${fd}dia" "M$([char]0xE9)dia"
$c = Fix $c "Prazo padr${fd}o" "Prazo padr$([char]0xE3)o"
$c = Fix $c "Checklist padr${fd}o" "Checklist padr$([char]0xE3)o"
$c = Fix $c "Restaurar padr${fd}o" "Restaurar padr$([char]0xE3)o"
$c = Fix $c "Vis${fd}o Geral" "Vis$([char]0xE3)o Geral"
$c = Fix $c "Descri${fd}${fd}o" "Descri$([char]0xE7)$([char]0xE3)o"
$c = Fix $c "Orienta${fd}${fd}o" "Orienta$([char]0xE7)$([char]0xE3)o"
$c = Fix $c "Observa${fd}${fd}es" "Observa$([char]0xE7)$([char]0xF5)es"
$c = Fix $c "Etapas de execu${fd}${fd}o" "Etapas de execu$([char]0xE7)$([char]0xE3)o"
$c = Fix $c "Regras de execu${fd}${fd}o" "Regras de execu$([char]0xE7)$([char]0xE3)o"
$c = Fix $c "Regras de conclus${fd}o" "Regras de conclus$([char]0xE3)o"
$c = Fix $c "execu${fd}${fd}o" "execu$([char]0xE7)$([char]0xE3)o"
$c = Fix $c "Arquivos necess${fd}rios" "Arquivos necess$([char]0xE1)rios"
$c = Fix $c "Obrigat${fd}ria" "Obrigat$([char]0xF3)ria"
$c = Fix $c "obrigat${fd}ria" "obrigat$([char]0xF3)ria"
$c = Fix $c "Revis${fd}o" "Revis$([char]0xE3)o"
$c = Fix $c "C${fd}digo" "C$([char]0xF3)digo"
$c = Fix $c "c${fd}pia" "c$([char]0xF3)pia"
$c = Fix $c "reutiliz${fd}veis" "reutiliz$([char]0xE1)veis"
$c = Fix $c "reutiliz${fd}vel" "reutiliz$([char]0xE1)vel"
$c = Fix $c "poss${fd}vel" "poss$([char]0xED)vel"
$c = Fix $c "N${fd}o vinculado" "N$([char]0xE3)o vinculado"
$c = Fix $c "impactar${fd}o" "impactar$([char]0xE3)o"
$c = Fix $c "Altera${fd}${fd}es" "Altera$([char]0xE7)$([char]0xF5)es"
$c = Fix $c "Vincula${fd}${fd}o" "Vincula$([char]0xE7)$([char]0xE3)o"
$c = Fix $c "Vincula${fd}${fd}es" "Vincula$([char]0xE7)$([char]0xF5)es"
$c = Fix $c "Filtros avan${fd}ados" "Filtros avan$([char]0xE7)ados"
$c = Fix $c "Criado at${fd}" "Criado at$([char]0xE9)"
$c = Fix $c "Atualizado at${fd}" "Atualizado at$([char]0xE9)"
$c = Fix $c "m${fd}nima" "m$([char]0xED)nima"
$c = Fix $c "Colunas vis${fd}veis" "Colunas vis$([char]0xED)veis"
$c = Fix $c "prefer${fd}ncia" "prefer$([char]0xEA)ncia"
$c = Fix $c "tarefas${fd}" "tarefas$([char]0x2026)"
$c = Fix $c "tarefas s${fd}o" "tarefas s$([char]0xE3)o"
$c = Fix $c "come${fd}ar" "come$([char]0xE7)ar"
$c = Fix $c "A${fd}${fd}es" "A$([char]0xE7)$([char]0xF5)es"
$c = Fix $c "P${fd}gina" "P$([char]0xE1)gina"
$c = Fix $c "poder${fd} ser" "poder$([char]0xE1) ser"
$c = Fix $c "autom${fd}ticamente" "autom$([char]0xE1)ticamente"
$c = Fix $c "Configura${fd}${fd}o" "Configura$([char]0xE7)$([char]0xE3)o"
$c = Fix $c "Tr${fd}fego" "Tr$([char]0xE1)fego"
$c = Fix $c "valida${fd}${fd}o" "valida$([char]0xE7)$([char]0xE3)o"
$c = Fix $c "Salvando${fd}" "Salvando$([char]0x2026)"
$c = Fix $c "revis${fd}o" "revis$([char]0xE3)o"
$c = Fix $c "n${fd}o est${fd}" "n$([char]0xE3)o est$([char]0xE1)"
$c = Fix $c "n${fd}o" "n$([char]0xE3)o"
$c = Fix $c "N${fd}o" "N$([char]0xE3)o"
$c = Fix $c "est${fd} " "est$([char]0xE1) "
$c = Fix $c "c${fd}digo" "c$([char]0xF3)digo"
$c = Fix $c "padr${fd}o" "padr$([char]0xE3)o"
$c = Fix $c "avan${fd}ado" "avan$([char]0xE7)ado"
$c = Fix $c "Avan${fd}ado" "Avan$([char]0xE7)ado"
$c = Fix $c "a${fd}${fd}es" "a$([char]0xE7)$([char]0xF5)es"
$c = Fix $c "a${fd}${fd}o" "a$([char]0xE7)$([char]0xE3)o"
$c = Fix $c "vis${fd}o" "vis$([char]0xE3)o"
$c = Fix $c "Ap${fd}s" "Ap$([char]0xF3)s"
$c = Fix $c "conclus${fd}o" "conclus$([char]0xE3)o"
$c = Fix $c "p${fd}gina" "p$([char]0xE1)gina"
# em dash fallback for "return" line
$c = Fix $c "return `"${fd}`"" "return `"$([char]0x2014)`""
# middle dot: " ? " where ? is FFFD
$c = Fix $c " ${fd} " " $([char]0xB7) "
# arrow char › U+203A
$c = Fix $c "`"${fd}`"" "`"$([char]0x203A)`""
# Any remaining FFFD -> em dash or remove
$c = Fix $c "${fd}" "$([char]0x2014)"

$rem = ($c.ToCharArray() | Where-Object {[int]$_ -eq 0xFFFD}).Count
Write-Host "Remaining FFFD: $rem"
$enc = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($f, $c, $enc)
Write-Host "Done"