// Ajuda (i) por tela (P-5, 08/10). Texto simples, em português, explicando o que cada campo faz. Uma lista por tela.
export const SECURE_BROWSER_HELP: Record<string, string> = {
  "Nome da conta": "Como esta conta aparece na lista (ex.: Instagram da loja). Serve só para você identificar.",
  "Endereço de entrada": "Endereço onde o navegador abre ao iniciar (a página de login do site). Só abre se o site estiver na lista de permitidos.",
  "Validade do login": "Por quantos minutos o login salvo vale. Passado esse tempo é preciso logar de novo. Entrar na sessão não renova a validade.",
  "Quem autorizar": "A pessoa que poderá usar esta conta no navegador seguro.",
  "Minutos de autorização": "Por quanto tempo a pessoa pode usar a conta nesta liberação.",
  "Motivo": "Por que você está liberando. Fica registrado no histórico de uso.",
  "Liberar para um grupo": "Libera para todos os usuários de um grupo de uma vez.",
  "Sites permitidos": "Somente estes sites abrem na sessão; qualquer outro endereço é bloqueado. Separe por vírgula.",
  "Tempo máximo": "Limite de minutos da sessão. Ao terminar, a sessão é encerrada.",
  "Aceito": "Confirma que li e aceito as regras de uso do navegador seguro.",
};

export const INTERNAL_TASKS_HELP: Record<string, string> = {
  "Título": "Nome curto da tarefa.",
  "Título da tarefa": "Nome curto da tarefa.",
  "Descrição": "O que precisa ser feito, com os detalhes para quem for executar.",
  "Descrição da tarefa": "O que precisa ser feito, com os detalhes para quem for executar.",
  "Status": "Em que etapa a tarefa está: a fazer, em andamento ou concluída.",
  "Prioridade": "O quão urgente é. Aparece em destaque no quadro.",
  "Prazo": "Data limite para concluir a tarefa.",
  "Responsável": "Quem vai executar a tarefa. É essa pessoa que recebe os avisos de prazo.",
  "Novo item do checklist": "Um passo pequeno da tarefa; marque quando concluir.",
  "Novo comentário": "Conversa sobre a tarefa; todos da equipe veem.",
  "Buscar tarefa": "Procura pelo título ou pela descrição.",
  "ID da agência ou empresa": "Código da agência ou empresa cujo quadro você quer abrir (somente administração).",
};

export const SETTINGS_HELP: Record<string, string> = {
  "Nome da Plataforma": "Nome que aparece no topo da plataforma e nos e-mails enviados.",
  "Descrição": "Texto curto que descreve a plataforma.",
  "E-mail": "Endereço de e-mail usado nesta configuração (remetente ou contato).",
  "Servidor SMTP": "Endereço do servidor que envia os e-mails (ex.: smtp.seudominio.com).",
  "Porta": "Porta do servidor de e-mail (normalmente 587 ou 465).",
  "Usuário SMTP": "Usuário de login do servidor de e-mail.",
  "Senha SMTP": "Senha do servidor de e-mail. Fica guardada com segurança e não aparece depois de salva.",
  "Evento disparador": "O que acontece na plataforma para este webhook ser chamado.",
  "URL": "Endereço que recebe o aviso do webhook.",
  "Método": "Forma de envio do aviso (normalmente POST).",
  "Ativo": "Desligado = não funciona, mas continua cadastrado.",
  "Tamanho Máximo de Arquivo (MB)": "Maior arquivo que um usuário pode enviar.",
  "Timeout de Sessão (minutos)": "Tempo sem uso até a plataforma pedir login novamente.",
  "Comprimento mínimo": "Quantidade mínima de caracteres da senha.",
  "Chave": "Identificador técnico (sem espaços nem acentos). Não muda depois de criado.",
  "Provedor": "Empresa que fornece o serviço de IA.",
  "Teto mensal (US$)": "Valor máximo de gasto por mês. Passando disso, a plataforma avisa.",
  "Alertar ao atingir (%)": "Percentual do teto em que o aviso é enviado.",
  "Modelo": "Nome do modelo de IA.",
  "Cobrança": "Como o modelo é cobrado: por tokens, imagem, minuto etc.",
  "US$/1M entrada": "Preço, em dólar, de cada 1 milhão de tokens enviados à IA.",
  "US$/1M saída": "Preço, em dólar, de cada 1 milhão de tokens devolvidos pela IA.",
  "US$ por unidade": "Preço, em dólar, de cada unidade (imagem, minuto, requisição).",
  "Permitir Novos Cadastros": "Desligado = ninguém consegue se cadastrar sozinho.",
  "Modo de Manutenção": "Ligado = só administradores entram; os demais veem um aviso de manutenção.",
  "Verificação de Email Obrigatória": "Ligado = o usuário precisa confirmar o e-mail antes de usar a plataforma.",
  "Exigir Letras Maiúsculas e Minúsculas": "A senha precisa misturar letras maiúsculas e minúsculas.",
  "Exigir Números": "A senha precisa ter ao menos um número.",
  "Exigir Caracteres Especiais": "A senha precisa ter ao menos um símbolo (ex.: ! @ #).",
};

export const PLAC_HELP: Record<string, string> = {
  "Ordem": "Posição do passo no plano (1, 2, 3…).",
  "Nome do passo": "Nome curto do passo do plano.",
  "Quem faz": "Quem executa este passo.",
  "Etapa do contrato": "Fase do contrato em que o passo acontece.",
  "Fase": "Fase do contrato em que o passo acontece.",
  "O que acontece neste passo": "Explicação simples do que é feito neste passo.",
  "Descrição do passo": "Explicação simples do que é feito neste passo.",
  "Prazo conta a partir de": "Data de referência do prazo (ex.: início do projeto).",
  "Conta a partir de": "Data de referência do prazo (ex.: início do projeto).",
  "D+ (dias depois)": "Quantos dias depois da data de referência o passo deve acontecer.",
  "Dias depois": "Quantos dias depois da data de referência o passo deve acontecer.",
  "Horas previstas": "Tempo estimado para o passo, em horas.",
  "Custo/hora (R$)": "Quanto custa cada hora deste passo, em reais.",
  "Custo por hora": "Quanto custa cada hora deste passo, em reais.",
  "Repetição (informativa)": "Só informativa: diz se o passo se repete (ex.: todo mês). Não cria tarefas sozinha.",
  "Repetição": "Só informativa: diz se o passo se repete (ex.: todo mês). Não cria tarefas sozinha.",
  "Prazo": "Data prevista do passo, calculada pelo plano.",
};

// Ajuda GERAL (P-5, 08/10): vale em todas as telas que não têm dicionário próprio (e como complemento nas que têm; o dicionário da tela, quando existe, vence).
// Só entram nomes de CAMPO (nunca valores como "Ativo"/"Pendente"), para não aparecer ícone em dados da tabela.
export const GLOBAL_HELP: Record<string, string> = {
  "Nome": "Nome como aparece na plataforma.",
  "Nome completo": "Nome completo da pessoa, como no documento.",
  "Sobrenome": "Sobrenome da pessoa.",
  "Razão social": "Nome oficial da empresa, como no CNPJ.",
  "Nome fantasia": "Nome pelo qual a empresa é conhecida no dia a dia.",
  "CNPJ": "Número do CNPJ da empresa (somente números ou com pontuação).",
  "CPF": "Número do CPF da pessoa (somente números ou com pontuação).",
  "E-mail": "Endereço de e-mail. Usado para login e para os avisos da plataforma.",
  "Email": "Endereço de e-mail. Usado para login e para os avisos da plataforma.",
  "E-mail de contato": "E-mail para a equipe entrar em contato.",
  "Telefone": "Telefone com DDD.",
  "Celular": "Celular com DDD (de preferência com WhatsApp).",
  "WhatsApp": "Número com WhatsApp, com DDD.",
  "Senha": "Senha de acesso. Use letras, números e símbolos.",
  "Nova senha": "Nova senha de acesso. Use letras, números e símbolos.",
  "Confirmar senha": "Repita a senha para garantir que digitou certo.",
  "Confirmar nova senha": "Repita a nova senha para garantir que digitou certo.",
  "Senha atual": "A senha que você usa hoje. Pedimos por segurança antes de trocar.",
  "Cargo": "Função da pessoa na empresa.",
  "Perfil": "Tipo de acesso: define o que a pessoa pode ver e fazer.",
  "Permissões": "O que a pessoa pode ver e fazer na plataforma.",
  "Status": "Situação atual do item (ex.: ativo, pendente, concluído).",
  "Descrição": "Texto que explica o item com mais detalhes.",
  "Título": "Nome curto do item.",
  "Observações": "Anotações livres. Não aparecem para o cliente, a menos que a tela diga o contrário.",
  "Observação": "Anotação livre. Não aparece para o cliente, a menos que a tela diga o contrário.",
  "Prazo": "Data limite para concluir.",
  "Data de início": "Quando começa.",
  "Data de término": "Quando termina.",
  "Data de vencimento": "Último dia para pagar sem atraso.",
  "Vencimento": "Último dia para pagar sem atraso.",
  "Valor": "Quantia em reais (R$).",
  "Valor total": "Soma de todos os itens, em reais (R$).",
  "Preço": "Quanto custa, em reais (R$).",
  "Desconto": "Quanto é abatido do valor, em reais ou em porcentagem.",
  "Quantidade": "Quantas unidades.",
  "Categoria": "Grupo em que o item se encaixa, para organizar e filtrar.",
  "Tipo": "Classificação do item.",
  "Responsável": "Pessoa encarregada deste item.",
  "Cliente": "Empresa ou pessoa para quem o trabalho é feito.",
  "Agência": "Agência responsável por este item.",
  "Empresa": "Empresa dona deste item.",
  "Projeto": "Projeto ao qual este item pertence.",
  "Produto": "Produto do catálogo ao qual isto se refere.",
  "Prioridade": "O quão urgente é. Itens mais prioritários aparecem em destaque.",
  "Endereço": "Endereço completo.",
  "CEP": "Código postal. Ao preencher, o endereço pode ser completado sozinho.",
  "Cidade": "Cidade do endereço.",
  "Estado": "Estado (UF) do endereço.",
  "Logradouro": "Rua, avenida ou similar.",
  "Número": "Número do imóvel ou do documento, conforme a tela.",
  "Complemento": "Apartamento, sala, bloco etc.",
  "Bairro": "Bairro do endereço.",
  "Site": "Endereço do site, começando com https://.",
  "Link": "Endereço (URL) que abre ao clicar.",
  "URL": "Endereço (link) da página ou do serviço.",
  "Anexos": "Arquivos que acompanham este item.",
  "Arquivo": "Arquivo enviado do seu computador.",
  "Imagem": "Imagem enviada do seu computador.",
  "Logo": "Logotipo da marca. De preferência com fundo transparente.",
  "Comissão": "Parte do valor que a pessoa ou agência recebe, em porcentagem ou reais.",
  "Chave PIX": "Chave Pix que recebe os pagamentos (CPF, CNPJ, e-mail, telefone ou aleatória).",
  "Banco": "Banco onde a conta é mantida.",
  "Agência bancária": "Número da agência do banco, sem o dígito.",
  "Conta": "Número da conta bancária, com o dígito.",
  "Buscar": "Digite parte do nome para filtrar a lista.",
  "Pesquisar": "Digite parte do nome para filtrar a lista.",
  "Ordenar por": "Escolha como a lista é organizada.",
  "Mensagem": "Texto que será enviado ou exibido.",
  "Assunto": "Título curto da mensagem.",
  "Motivo": "Por que a ação está sendo feita. Fica registrado no histórico.",
  "Idioma": "Idioma em que a plataforma é exibida.",
  "Fuso horário": "Fuso usado para exibir datas e horários.",
};
